matrix-org/matrix.org

- jekyll/_posts/projects/2015-06-02-riot-android.md
Seems like the link still points to the app with an old name.
> Update download link after app rename

- jekyll/_posts/guides/2015-08-19-faq.md
As far as I'm aware, Jira is no longer being used and the link to it in the FAQ returns 404. So, this removes the link and instead adds a link to the GitHub organization.
> Replace broken link to Jira with link to GitHub

- jekyll/_posts/projects/2014-08-12-synapse.md
The dockerfile is now maintained by aventer and the images are at a different location on docker hub.
> Changed Dockerfile location after handover

- jekyll/_posts/projects/2017-06-27-mautrix-appservice-go.md
- jekyll/_posts/projects/2017-09-29-maulabbot.md
- jekyll/_posts/projects/2017-11-28-mautrix-telegram.md
- jekyll/_posts/projects/2018-03-15-gomuks.md
Added language, license and repo metadata to mautrix-appservice-go, maulabbot and mautrix-telegram and made links in the description of those projects and gomuks more consistent.
> Add new metadata to my projects

- jekyll/_posts/projects/2018-09-13-SimpleMatrix.md
It seems like it worked on Github but on the Matrix Page the Title did not get rendered as a Title. I think the reason is that I missed these 2 whitespaces. Sorry for that
> Fix Title in SimpleMatrix project file

- jekyll/_posts/projects/2014-08-12-synapse.md
Reason for package moving, from net to net-im because it is a more appropriate category.
> FreeBSD package location has moved.

- jekyll/_posts/guides/2016-10-18-e2e_implementation.rst
Attempt to bring the implementation guide up-to-date with the current state of E2E in Matrix.
It can't be merged before https://github.com/matrix-org/matrix-doc/pull/1465, https://github.com/matrix-org/matrix-doc/pull/1420, and https://github.com/matrix-org/matrix-doc/pull/1284 are, since it contains links to those parts.
Signed-off-by: Valentin Deniaud \<valentin.deniaud@inpt.fr\>
> Update on E2E implementation guide

- unstyled_docs/spec/server_server/r0.1.0.html
As per https://github.com/matrix-org/matrix.org/pull/228 until https://github.com/matrix-org/matrix.org/issues/230 exists.
> Add outdated spec warning to r0.1.0 of s2s

- jekyll/_posts/projects/2014-08-12-synapse.md
See https://github.com/vector-im/riot-web/issues/9497 (applies to more than just Olm)
See also https://github.com/matrix-org/synapse/pull/5067
> Use packages.matrix.org for packages

- gatsby/blog/2019-04-11/security.mdx
- gatsby/gatsby-config.js
- gatsby/package-lock.json
- gatsby/package.json
Apparently the html output was just broken on that version of gatsby-mdx. When I update it to version 0.6.2 the RSS feed works but if I update it to the latest version (0.6.3) I get some awful react error when building the site. No idea up with that but at least the RSS feed works.
Also had to remove a random character from one of the blog posts to get the XML to be valid. We may need some way of validating blog posts so those characters don't get added and silently break the feed.
Fixes #408
> Fix the RSS feed so it shows the full post (#408)

- gatsby/src/pages/index.js
(Also this is how Gatsby says to do local links https://www.gatsbyjs.org/docs/gatsby-link/)
> Link to the actual blog post for Matrix 1.0 instead of /blog

- gatsby/content/docs/2015-08-14-getting_involved.mdx
Synapse's built-in webclient is deprecated. Even if code still exists and works (I'm not sure if it does), it's not appropriate to discuss such details on the "getting involved" page.
> Remove obsolete para about synapse webclient

- gatsby/content/projects/2017-08-31-fractal.mdx
> migrate link per Gnome's GitLab notice

- gatsby/src/pages/docs/guides.js
I hope this is all I need to change. If not I add required changes as well. (Never used gatsby before and only did a quick edit from the web view of github)
> Add a section for Translations guides

- gatsby/content/projects/2015-03-10-irc-bridge.mdx
... not sure if the link in the main text should be removed or not: other bridges also have the redundancy:
https://github.com/matrix-org/matrix.org/blame/943c21e68aa76d498dd8bd29886797c3a854035c/gatsby/content/projects/2015-09-18-matrix-appservice-slack.mdx#L32
> Add structured repo link for irc bridge

- gatsby/gatsby-config.js
The "title" of the feed should describe the original site, not the feed itself.
> Remove "RSS Feed" from site title of feed

- content/.well-known/matrix/client
This is just so that we can route matrix client traffic separately from website traffic if we wish (by pointing matrix-client.matrix.org to a different HAProxy)
> Route matrix client traffic to matrix-client.matrix.org

- gatsby/content/projects/2014-12-10-ivar2-matrix-irc-bot.mdx
Because the long form is "it is written in Lua".
Used on: https://matrix.org/docs/projects/bots/
> Grammar fix: its -> it's

- gatsby/src/pages/faq.js
This adds a space before the sydent link.
> Add space before link

- gatsby/content/projects/2020-01-18-mx-puppet-discord.mdx
- gatsby/content/projects/2020-01-18-mx-puppet-slack.mdx
- gatsby/content/projects/2020-01-18-mx-puppet-twitter.mdx
Twitter accidentally had the tox icon and set `featured:true`
Reason why it isn't set in tox: It currently only works with an old version of node due to a node-ffi bug
Reason why it isn't set in instagram: There is currently a bug when logging in with 2fa
> Fix mx-puppet-bridge information

- gatsby/content/projects/2018-09-05-mxbridge.mdx
- gatsby/content/projects/2020-01-18-miitrix.mdx
- gatsby/content/projects/2020-01-18-mx-puppet-discord.mdx
- gatsby/content/projects/2020-01-18-mx-puppet-instagram.mdx
- gatsby/content/projects/2020-01-18-mx-puppet-slack.mdx
- gatsby/content/projects/2020-01-18-mx-puppet-tox.mdx
- gatsby/content/projects/2020-01-18-mx-puppet-twitter.mdx
- gatsby/content/projects/bots/matrix-notification-bot.mdx
#671 
Fix capitalization for a few projects that had TypeScript, Javascript, and Elixir capitalized incorrectly.  Also fixed formatting of license name for one.
This prevents some duplicate entries from showing on https://matrix.org/docs/projects/try-matrix-now
> Metadata tidying for projects

- gatsby/content/projects/2015-03-10-irc-bridge.mdx
- gatsby/content/projects/2019-06-18-matrix-puppet-groupme.mdx
- gatsby/content/projects/2020-01-18-mx-puppet-discord.mdx
- gatsby/content/projects/bridges/jojiis-mail-bridge.mdx
- gatsby/src/pages/bridges.js
Fixed incorrect spelling, punctuation, and supplied missing words in the https://matrix.org/bridges/ page.
Signed-off-by: teikjun <teikjunhci@gmail.com>
> fix typos in bridges page

- gatsby/content/blog/2019/07/python-nio.mdx
- gatsby/content/blog/2020/03/2020-03-23-synapse-1.12.0-release.mdx
- gatsby/content/docs/2018-09-21-usage-of-the-matrix-js-sdk.mdx
- gatsby/content/docs/free-small-matrix-server.mdx
- gatsby/content/docs/matrix-js-bot-sdk-intro.mdx
- gatsby/content/docs/python-nio.mdx
- gatsby/content/docs/whatsapp-bridging-mautrix-whatsapp.mdx
This fixes two warnings about `sh` and `unix` not being recognized languages in PrismJS.
A warning `warn code block or inline code language not specified in markdown. applying generic code block` remains; putting languages in for all of the code blocks that do not have languages specified did not fix that.  Maybe a language would have to be specified for all of the inline code blocks too.
> Fix code block languages

- gatsby/content/projects/2015-01-06-matrix.org-python-sdk.mdx
Hopefully closes #590 although I don't entirely understand how Gatsby works.
> Deprioritize unmaintained python sdk

- content/.well-known/matrix/server
Move federation traffic for the matrix.org synapse server away from `https://matrix.org:8443/` to `https://matrix-federation.matrix.org:443/`
moving federation traffic over to using .well-known because we can't route it because the SRV mechanism sends the Host: and SNI server_name as `matrix.org`, not  `matrix-federation.matrix.org`
> Deploy a .well-known/matrix/server file.

- gatsby/src/pages/contact.js
I think it makes sense to list all email addresses, although security also has a separate page
> mention security@matrix.org in Contact page

- gatsby/content/docs/online-events.mdx
So I had to set up livestreaming this weekend for an event and decide to use our blog post!
It worked out in the end, but the suggested repo for nginx-rtmp-module just wouldn't compile with the latest nginx. Plus seeing the last commit being in 2017 made me think hard about turning around. I did try it, but it wouldn't even compile with the latest stable release of nginx.
I looked up some guides for the process and found everyone recommending a fork of this module at https://github.com/sergey-dryabzhinsky/nginx-rtmp-module. This one seems to be actively maintained, and sure enough compiled fine.
I think we should recommend people use this up-to-date version instead of the current one.
> Replace link to nginx-rtmp-module with a maintained fork

- gatsby/content/projects/2018-02-23-perl6-matrix-client.mdx
Raku is also not perl (5)
Renaming of perl6 -> raku: https://docs.raku.org/language/faq#What's_the_difference_between_Raku,_Rakudo_and_Perl_6?
Some renaming inside the project: https://github.com/matiaslina/perl6-matrix-client/commit/e50b8fa9e02b19ece80ebeb576051e451d3a7812
> Raku is the new name for perl6

- gatsby/src/pages/try-now.js
I cleaned up the Try-Matrix page (that lives behind the Call-to-action-button in the navbar)(#743, #665) and added a link to a server list (#586, #95, to some extent #134)
> Cleaning up try now page

- gatsby/content/blog/2020/06/2020-06-19-twim.mdx
Mozilla WebThings is the common term for the project.
https://iot.mozilla.org
> Correct term: Mozilla Thing -> Mozilla WebThings

- gatsby/content/projects/2018-12-27-fluffychat.mdx
Fluffychat now has their website at https://fluffychat.im/en/, not http://fluffy.chat (old website gives an ugly HTTP 401).
Their official repo links to the new site already: https://gitlab.com/ChristianPauly/fluffychat-flutter
> Fluffychat website has moved

- gatsby/src/pages/docs/guides.js
The document was renamed from `.rst` to `.md`.
> Update link to synapse opentracing document

- implementation-guides/server/book.toml
Was missing `implementation-guides` folder from the source code link.
> Fix link to book source code

- gatsby/content/projects/2014-06-09-riot.mdx
- gatsby/content/projects/bridges/matrix-keybase.mdx
Only riot-web was using "No longer maintained" instead of "Not actively maintained"
Closes #772 
```bash
matrix.org/gatsby/content/projects$ cat *.mdx */*.mdx | grep maturity: | sed -E 's/\s+#.+//' | sort -u
maturity: Alpha
maturity: Beta
maturity: Early Alpha
maturity: Early Beta
maturity: Late Alpha
maturity: Late Beta
maturity: Not actively maintained
maturity: Released
maturity: Stable
```
> Update keybase project status and fix riot-web maturity

- gatsby/src/components/MXProjectCard.js
As a beginner looking for inspiration to write a bot in language X, this
allows me to filter bots of interests without changing page (clicking on
each bot individually).
Signed-off-by: Pamplemousse <xav.maso@gmail.com>
> Add language to bots overview

- jekyll/_sass/_base.scss
- jekyll/css/docs_overrides.css
- jekyll/css/site_overrides.css
Over in https://github.com/matrix-org/matrix-doc/issues/2805 I suggested making some changes to the spec CSS to make it more readable. But some of the relevant CSS is coming from the Jekyll builder over here. Specifically:
* `font-weight: 300` makes the text harder to read than a normal weight
* `color: #666` is worse for contrast than `#333`, and `#333` is the [style guide recommendation](https://matrix-org.webflow.io/style-guide)
Before these changes, the spec looks like:
After these changes, the spec should look like:
Unfortunately I'm not sure how to build the Jekyll site locally to test this properly, but I'm happy to do so if you can give me some pointers.
> Tweak Jekyll styles for readability

- gatsby/content/projects/2014-08-12-synapse.mdx
We (Cloudron team) have been maintaining packages for Synapse and Element for quite a while now. We also have many users of Synapse on our platform (https://forum.cloudron.io/category/50/matrix-synapse-element). Would be great to have Cloudron listed as an installation option alongside others.
> Add Cloudron as installation method

- .buildkite/pipeline.yaml
- implementation-guides/application-services/book.toml
- implementation-guides/client/book.toml
- implementation-guides/index.html
- implementation-guides/server/book.toml
- implementation-guides/theme/index.hbs
1. I forgot to add the new guides to the CI
2. The books built by CI used the wrong theme (and the CSP added there was wrong, but we seem to do CSP in the apache anyway)
3. Add a *very* basic index.html with links to the book, reusing the same CSS as the books. This is really just a place holder.
> Fix up implementation guides

- gatsby/content/docs/2019-04-29-moderation.mdx
Small fix. Found this while browsing https://matrix.org/docs/guides/moderation#power-levels, the backticks were out of control.
> Fix markdown in /op example

- gatsby/content/projects/bots/matrix-feeder.mdx
This PR adds `matrix-feeder` to the bots site.
Matrix-feeder is a monitoring bot that can be added to multiple rooms and will relay media to a predefined room.
**URL:** https://github.com/dragonchaser/matrix-feeder
> Add matrix-feeder

- gatsby/src/pages/faq.js
Changed previous outdated link (looks like they moved federation docs from their README to a separate file).
> Update synapse federation docs link

- gatsby/content/docs/2015-08-14-getting_involved.mdx
Changed some Riot/Vector branding and links to Element. Also added spaces in some instances of the word web client.
> Changed some branding and spelling

- gatsby/content/projects/clients/ditto.mdx
As stated on https://dittochat.org/ > Connect > Matrix Room
The corrected room (elequin.io) does not seem to work anymore.
> Update Matrix room for Ditto Chat

- gatsby/content/blog/2020/12/2020-12-07-gitter-now-speaks-matrix.mdx
Fix markdown formatting from Google doc
Fix formatting in https://matrix.org/blog/2020/12/07/gitter-now-speaks-matrix
> Fix markdown formatting from Google doc

- gatsby/content/blog/2020/12/2020-12-07-gitter-now-speaks-matrix.mdx
Fix mismatch between talking about the Scala room and linking the Node.js one
Happened after I suggested using a more active room in https://github.com/matrix-org/matrix.org/pull/899. That person was after showing a room where the community name was different from the room to make the syntax more clear.
> Fix mismatch between talking about the Scala room and linking the Node.js one

- gatsby/content/projects/2016-02-10-matrix-appservice-gitter.mdx
- gatsby/content/projects/2020-01-04-native-gitter-bridge.mdx
Update [Gitter bridge section](https://matrix.org/bridges/) to point to the new native bridge
Fix https://github.com/matrix-org/matrix.org/issues/903
> Update Gitter bridge section to point to the new native bridge

- gatsby/content/projects/2016-02-10-matrix-appservice-gitter.mdx
- gatsby/content/projects/2020-01-04-native-gitter-bridge.mdx
Fix some formatting typos with the Gitter bridge section: https://matrix.org/bridges/#gitter
Part of https://github.com/matrix-org/matrix.org/issues/903
Follow-up to https://github.com/matrix-org/matrix.org/pull/919
> Fix some formatting typos with the Gitter bridge section

- gatsby/src/components/Navigation.js
The `Try Now` button requires clicking through four pages before being presented with a login.  
Try Now > Start Element Web > Try Element > Open in Browser
This simplifies the process somewhat:
Try Now > Open in Browser
> reduce number of clicks required by "Try Now"

- gatsby/src/components/Footer.js
> Changed the copyright year in the footer from 2020 to 2021

- gatsby/content/blog/2019/10/2019-10-04-twim.mdx
The mentioned user deleted their profile and it was subsequently registered by another as a broken link hijacking POC. No risk, but may confuse someone in the unlikely event that they follow it.
> Remove expired Github profile link.

- gatsby/content/projects/other/node-red-contrib-matrixbot.mdx
Node-RED nodes to read and send messages and files (photos) to Matrix chatrooms.
> Add node-red-contrib-matrixbot to Other

- .gitignore
- scripts/update_docs.sh
- unstyled_docs/spec/appendices.html
This PR is part of unfreezing the spec as a whole after the spec redesign has launched: https://github.com/matrix-org/matrix-doc/issues/3055
Essentially we'd like to redirect the unstable versions of the old spec to the new spec site (https://spec.matrix.org). Unfortunately, we can't do that for the appendices page as there is no stable vs. unstable appendices page. It's never been versioned. As such, if we redirected it then any links to the appendices in the stable versions of the legacy spec would take you to the appendices page on the new spec - which would be very weird.
Thus, this PR freezes the appendices page in time. We'll be setting up redirects for all of the `/unstable` spec pages, as well as the `/proposals` page, as with the former the user consciously chooses to view the …
> Freeze the current appendices.html file for the legacy spec

- gatsby/content/blog/2021/04/2021-04-15-old-gitter-bridge-eol.mdx
Add blog announcing EOL for the old Gitter bridge
Draft: https://docs.google.com/document/d/1kX_paNJnljwqW4zb4RLzw9zYxTMZW_7S49T0O6yRBBs/edit
Thanks to @Half-Shot @paulinalundin @ara4n for reviewing! :ox:
> Add blog announcing EOL for the old Gitter bridge

- gatsby/content/blog/2015/04/904.mdx
Currently, there is only a small note at the bottom of the article, which also is a dead link, that there is an up-to-date version of this tutorial.
This commits adds a more aggressive note at the beginning of the tutorial, as very few of the configs in the article stayed that way until today,
but the blog post itself shows up in search engines pretty high up
> docs: mention up-to-date tutorial more aggressively

- gatsby/content/blog/2021/05/2021-05-05-synapse-1.33.0-released.mdx
> Synapse 1.33.0

- gatsby/content/blog/2021/05/2021-05-07-twim.mdx
I had gotten that wrong. It should say `!unlink` instead of `!unbridge`.
https://github.com/matrix-org/matrix-appservice-irc/pull/1298
> 2021-05-07-twim.mdx: New IRC command is !unlink

- gatsby/content/docs/2016-05-05-client-server.mdx
- gatsby/src/pages/docs/develop.js
* Travis has renamed his article after the Riot->Element rebranding.
* In the article "Client Server API" the backslashes are visible.
* I find the Feedback overlay to be incredibly annoying. Dismissing it brings it back several times even when staying on the same article. As a reader on a mobile phone, I wish it wasn't a floating overlay but a form at the bottom of the page.
> Update "Riot->Element" in article title and remove backslashes

- README.md
Remove need to install `gatsby` as a global dependency
Use the built-in npm scripts which already have `gatsby`
already on the path. Already in place at [`gatsby/package.json#L58`](https://github.com/matrix-org/matrix.org/blob/1397f009d4474a7001071bec5648a05cb58e0684/gatsby/package.json#L58)
Relevant docs, https://docs.npmjs.com/cli/v7/using-npm/scripts#path
> Remove need to install `gatsby` as a global dependency

- gatsby/src/components/Subline.js
- gatsby/static/css/webflow-overrides.css
Vertically space reading content more and consistently.
This is only a basic pass to make a blog post more readable. Lots more to improve in future iterations.
The screenshots from Windows are a lot better to review imo because they aren't retina huge but didn't want to scare anyone off with the unfamiliar font so macOS is available. Might be easier to check this out locally and compare to the live version of the site.
<details>
<summary>Screenshots from macOS</summary>
Before | After
--- | ---
Before | After
--- | ---
</details>
<details>
<summary>Screenshots from Windows</summary>
Before | After
--- | ---
Before | After
--- | ---
</details>
> Vertically space reading content more and consistently

- gatsby/static/css/webflow-overrides.css
Hang link anchors off to the side so heading text aligns with body
Before | After
--- | ---
Responsive:
> Hang link anchors off to the side so heading text aligns with body

- gatsby/content/projects/clients/element.mdx
> Use Element instead of riot.im in some links

- gatsby/content/projects/bridges/heisenbridge.mdx
:airplane: Whoosh, a challenger appears! :partying_face: 
I looked up other projects along the template to get it set up like the other bridges were so it shows up below matrix-appservice-irc. I don't know if it's allowed to add the featured flag so advice if I need to revise this.
Thanks.
> Add Heisenbridge to IRC bridges

- gatsby/content/projects/clients/element.mdx
The riot COPR is out of date. Link to the new element one.
> Update link to element Fedora COPR repository

- gatsby/content/docs/2019-04-29-moderation.mdx
2019 has been and gone, so remove future-tense references to 2019. The actual validity of the information should be verified by a contributor who is familiar with moderation features.
> [minor] Remove references to 2019 in Moderation guide

- gatsby/content/projects/clients/schildichat-desktop.mdx
Till now it's missing although added.
> Make SchildiChat Web/Desktop actually appear under clients

- gatsby/content/projects/clients/pattle.mdx
- gatsby/content/projects/sdks/matrix-dart-sdk.mdx
These are no longer maintained and frequently confuse people, so it's best not to have them linked up front. Pattle is also no longer available in app stores.
> Un-feature Pattle and Matrix Dart SDK.

- gatsby/src/pages/docs/guides.js
These both use Python 2 and link to out of date Riot links. They also make bad recommendations, the first one tells you to  use a matrix subdomain in your server name and the second one doesn't use Postgres.
> Remove two old guides for installing Synapse

- gatsby/content/blog/2021/06/2021-06-30-synapse-1.37.1-released.mdx
From an e-mail with the subject: "[BLOG] A typo on the latest blog"
In my opinion this is not adding a lot of meaning. It seems pretty clear that a CAPTCHA would be added.
Still I want to bring this suggestion to you, as an e-mail proposed to make this change.
> [BLOG] A typo on the latest blog (emailed suggestion)

- gatsby/content/blog/2021/07/2021-07-13-synapse-1.38.0-released.mdx
(Do not merge until Synapse 1.38 is actually released; adjust the date if that slips past Tuesday)
> Release Synapse 1.38.0

- gatsby/package.json
This way one can cleanup with `npm run clean` even though they don’t have gatsby installed system wide (as suggested by the README).
> Add gatsby clean as npm script

- gatsby/content/projects/bridges/matrix-puppeteer-line.mdx
Make the LINE bridge appear
As pointed out @LecrisUT, https://github.com/matrix-org/matrix.org/pull/1019#issuecomment-890634897
http://localhost:8000/bridges/#line
> Make the LINE bridge appear

- gatsby/content/projects/bots/hwittenborn-matrix-faq.mdx
This bot serves the same function as [Matrixcoffee/FAQBot](https://matrix.org/docs/projects/bot/faq-bot) from an end-user perspective of actually interacting with the bot, but the backend for configuration has some notable differences, such as allowing the specification of a prefix (not sure if FAQBot allows that or not) and specifying the FAQ messages in Markdown instead of Org Mode.
> Added listing for matrix-faq bot

- gatsby/content/projects/clients/mnotify.mdx
The repository was moved off of sr.ht.
> clients: mnotify: update homepage and repo links

- gatsby/content/docs/2019-04-29-moderation.mdx
Update qualifying statement about why upgrading a room is probably fine if you need to. The upgrade process itself is not in the testing stage anymore but does still have some rough edges when it comes to the user experience.
Fix https://github.com/matrix-org/matrix.org/issues/1060
> Update qualifying statement why upgrading a room is probably fine if you need to

- gatsby/content/docs/2017-03-11-types-of-bridging.mdx
- gatsby/src/pages/faq.js
Remove outdated [`matrix-appservice-gitter`](https://github.com/matrix-org/matrix-appservice-gitter) reference.
Don't want to confuse people on how the new Gitter bridge works as this old bridge doesn't even run anymore.
> Remove outdated Gitter bridge reference

- .github/workflows/build-matrix.org.yml
- scripts/update_docs.sh
This is intended to replace the existing Buildkite one, but the latter can be removed at a latter point when all the bits are in place. The workflow can be seen working for the gh-actions branch at [the Actions tab](https://github.com/matrix-org/matrix.org/actions).
> 👷 Port CI to Github Actions

- gatsby/content/docs/free-small-matrix-server.mdx
Is shell or sh the right choice for syntax highlighting shell code? How do you feel about removing the 'small' from the name? Oracle now offers enough resources to run a quite beefy matrix server.
> Update the free matrix server article/guide

- .github/workflows/build-matrix.org.yml
- gatsby/src/pages/docs/projects/try-matrix-now.js
This caches the `.cache` and `public` directories, as [suggested by the Gatsby documentation](https://www.gatsbyjs.com/docs/reference/release-notes/v3.0/#incremental-builds-in-oss) (it’s worth noting we are still on 2.24).
From running the workflow several times for that commit, I can see that the cache is saved and restored, but I don’t notice a significant performance improvement. I suggest we merge it (assuming I didn’t break anything) and see how it behaves over a series of commits. I reckon worst case is we don’t save anything.
> 👷 Cache gatsby builds

- gatsby/content/blog/2021/11/2021-11-17-synapse-1.47.0-released.mdx
Making this a PR to test CI
Preview: https://pr1118--matrix-org-previews.netlify.app
> Synapse 1.47 announcement

- gatsby/src/pages/security-disclosure-policy.js
Just needs a sanity check. Tested locally, looks good to me.
Preview: https://pr1127--matrix-org-previews.netlify.app
> Add request not to send reports regarding SPF/DMARC.

- rapidoc/index.html
This depends on https://github.com/matrix-org/matrix-doc/pull/3542 and should not be merged before it lands.
This will also solve issues with broken links.
Fixes https://github.com/matrix-org/matrix-doc/issues/3507
Preview: https://pr1141--matrix-org-previews.netlify.app
> 👽️ Use new public definition file

- gatsby/content/legal/2019-08-22-privacy_notice.mdx
Without the schema this is seen as a relative link: https://matrix.org/legal/element.io/privacy
In the [original document](https://github.com/vector-im/policies/blob/master/docs/matrix-org/privacy_notice.md) this is not a link.
Preview: https://pr1216--matrix-org-previews.netlify.app
> Privacy Notice: Correct Element Privacy Policy URL

- gatsby/content/docs/introduction.mdx
Since Hello-Matrix has been abandoned for a while now, making any updates to the list impossible. (The pings are still running though.)
For reference, Hello-Matrix currently features 14 homeservers,
* 4 of which are no longer operational:
* chat.privacytools.io
* junta.pl
* alternanet.fr
* matrix.allmende.io
* 1 of which is in the process of shutdown: feneas.org
* 1 of which is private: hackerspace.be
Preview: https://pr1221--matrix-org-previews.netlify.app
> Docs: Replace Hello-Matrix with JoinMatrix

- gatsby/src/pages/hosting.js
GoMatrixHosting announced they were shutting down their services,
as stated in https://gomatrixhosting.com/2022/02/07/goodbye-gomatrixhosting/
> Remove gomatrixhosting from hosting solutions

- gatsby/content/docs/free-small-matrix-server.mdx
Preview: https://pr1255--matrix-org-previews.netlify.app
> Update article about free home server using Oracle Cloud

- gatsby/src/pages/docs/guides.js
I changed the URL of my guide. A redirect exists, but it passes through an additional nginx reverse proxy. Putting the proper URL in the guide will maximize its availability!
Original PR (when I added my guide) : https://github.com/matrix-org/matrix.org/pull/731
> Update URL to my French introduction to Matrix

- gatsby/content/projects/bridges/matrix-rocketchat.mdx
As written on https://github.com/exul/matrix-rocketchat the project is not actively maintained anymore.
> Set matrix-rocketchat to not actively maintained

- gatsby/content/projects/other/olm.mdx
These previously came up with a "no file named docs/[meg]olm.rst on master" message from GitLab.
Preview: https://pr1291--matrix-org-previews.netlify.app
> Fix olm/megolm links

- gatsby/content/blog/2022/04/2022-04-05-synapse-1.56.mdx
Because they're not. I misread the upgrade notes.
Preview: https://pr1309--matrix-org-previews.netlify.app
> Don't say groups are disabled

- gatsby/content/blog/2022/04/2022-04-19-synapse-1.57.md
Synapse 1.57 is not going out until next week, but I've written the release blog post in advance as I won't be able to do it then.
Next week, when 1.57 goes out, people should:
1. make any amendment necessary to this PR (ofc this point can be done in advance)
2. merge the PR
3. wait for the website to redeploy. This can take up to 30min after the CI for `master` has finished running. If the blog post is still not visible after that, it's possible that the redeploy of the website failed, in which case the best thing to do is nudge someone to rebuild it manually.
4. get someone with access to the @matrixdotorg twitter account and ask them to tweet a link to the post with a small summary text. Previous release tweets can be seen [here](https://twitter.com/search?q=filter%3Alinks%20-filter%3Ar …
> Synapse 1.57

- gatsby/src/components/MXProjectHeader.js
It looks like it was originally added as a part of the new SDKs page, but later leaked into bridges when that page was updated. For bridges, it's very confusing as there's no link and it can be interpreted as the bridge being hosted on matrix.org. For SDKs, it just links to a page that has the exact same content as the current page, so I don't think it's necessary at all (e.g. on https://matrix.org/sdks/#mautrix-go it links to https://matrix.org/docs/projects/sdk/mautrix-go)
Preview: https://pr1306--matrix-org-previews.netlify.app
> Remove confusing "{project} on matrix.org" text

- gatsby/static/css/how-it-works.css
- gatsby/static/js/how-it-works.js
Fixes #1053 , used the suggestion from @MadLittleMods
> Fix unable to select text on animation bug (#1053)

- gatsby/content/blog/2022/05/2022-05-06-twim.mdx
some mscs were linked to https://github.com/matrix-spec-proposals instead of https://github.com/matrix-org/matrix-spec-proposals
Preview: https://pr1329--matrix-org-previews.netlify.app
> Fix some URLs

- gatsby/content/blog/2022/05/2022-05-18-synapse-1.59.mdx
Preview: https://pr1335--matrix-org-previews.netlify.app
> Synapse 1.59

- gatsby/content/projects/bridges/MandM-bridge.mdx
Hey guys,
as Murmur does not have gRPC anymore (https://github.com/mumble-voip/mumble/commit/e909c239d7ed2f5473e9085ee5ec7fbc4ed68f26), i've decided to write a bridge which uses the ICE interface to communicate with murmur instead.
It's my first matrix related project so i'm happy to do changes / improvments to the bridge repo if they are required :)
Kind regards
Karl
> Add MandM-bridge (Matrix Mumble bridge)

- .github/_typos.toml
Broke in https://github.com/matrix-org/matrix.org/pull/1399 due to a stylised 'the': `tha'`.
This PR ignores the entire file from typo checking, and thus the specific false-positive.
> Fix typo CI for TWIM 20220812

- gatsby/src/pages/faq.js
- scripts/_url-directory.md
The sentence was missing several words, and using a non-published
address for the room.  Make it a complete sentence and change the link
to use the canonical address.
> Fix Synapse support room reference in FAQ

- gatsby/src/pages/faq.js
- scripts/_url-directory.md
And mention that other networks are also bridged.
> FAQ: Replace freenode references with libera.chat

- gatsby/src/templates/category.js
It goes to /posts/ rather than the actual category right now.
See https://matrix.org/blog/category/this-week-in-matrix/33 for example.
Preview: https://pr1354--matrix-org-previews.netlify.app
> Fix 'previous' link in categories on pages ≥ 3

- content/.well-known/assetlinks.json
Add Android asset links to support app intents (opening `app.element.io` will open the Android app when installed): `/.well-known/assetlinks.json`
Fix https://github.com/matrix-org/matrix-ansible-private/issues/5223 which unblocks https://github.com/vector-im/element-android/pull/6225 to solve https://github.com/vector-im/element-android/issues/5748
Preview: https://pr1431--matrix-org-previews.netlify.app
> Add Android asset links to support app intents (`/.well-known/assetlinks.json`)

- gatsby/src/pages/faq.js
The communities feature was removed. The section is replaced with a section about spaces instead.
A defintion for spaces has been added. A note about groups and communities being deprecated has been added to their definitions in the gloassary.
Fixes #1380
Preview: https://pr1415--matrix-org-previews.netlify.app
> FAQ: Overhaul "What are communities"

- gatsby/content/projects/bots/matrix-asgi.mdx
- gatsby/content/projects/bots/matrix-webhook.mdx
Hi,
This is adding a new project of mine, https://github.com/nim65s/matrix-asgi.
While here, I'm updating matrix-webhook a bit.
Preview: https://pr1398--matrix-org-previews.netlify.app
> Add Matrix-ASGI project

- gatsby/content/blog/2022/09/2022-09-02-twim.mdx
TWIM did link to a post in the category instead of the post itself. Therefor, this link died after new posts were added.
> Fix dead link in TWIM post

- gatsby/content/blog/2022/09/2022-09-16-twim.mdx
When copying the text over, a link to a coworking space was copy-pasted, too. This remove the unrelated link.
Preview: https://pr1445--matrix-org-previews.netlify.app
> Remove copy-pasted error

- gatsby/content/projects/bridges/mx-puppet-discord.mdx
mx-puppet-discord does supports presence and typing notifications both ways since nov 2020.
See https://github.com/matrix-discord/mx-puppet-discord/commit/0a21bb8ad5b9c41ad346de99df5a38d384d9c9ef
And Discord has threads now, which mx-puppet-discord does not support.
Preview: https://pr1222--matrix-org-previews.netlify.app
> Updates to the mx-puppet-discord project

- gatsby/content/blog/2022/09/2022-09-30-twim.mdx
Just some minor fixes to improve the news.
Preview: https://pr1474--matrix-org-previews.netlify.app
> Fix typos in the TWIM announcement for the matrix-widget-api

- content/.well-known/security.txt
Fixes #1468
This adds a https://securitytxt.org/ file. This seemingly starts to get a common thing for security research and seems to be a nice to have along the security disclosure page.
Preview: https://pr1469--matrix-org-previews.netlify.app
> Add security.txt

- templates/post.html
(Note this is against zola not against gatsby)
This implements https://developers.google.com/search/docs/appearance/structured-data/article for the blog articles.
> Add NewsArticle schema data to the post template

- templates/clients.html
Fixes unnecessary get_url which broke the images.
> [Zola] Fix preview image path for the clients page

- config.toml
- sass/_base.scss
The changes to the CSS are removing the old style and adding the recommendations from https://www.getzola.org/documentation/content/syntax-highlighting/#styling-codeblocks
> [Zola] Change to visual studio style codeblocks

- content/blog/2022/09/2022-09-02-twim/index.md
- content/blog/2022/09/2022-09-09-twim/index.md
- content/blog/2022/09/2022-09-16-twim/index.md
- content/blog/2022/09/2022-09-23-twim/index.md
- content/blog/2022/09/2022-09-27-thirdroom/index.md
- content/blog/2022/09/2022-09-30-twim/index.md
This adds the very new lazy loading argument to the YouTube iframes. ( https://html.spec.whatwg.org/multipage/urls-and-fetching.html#lazy-loading-attributes ) This currently will only work on chrome based browsers ( https://caniuse.com/loading-lazy-attr ) But seems to roll out on next safari and Firefox in the future too. This should allow the page to load faster when this lands in more browsers, since the YouTube embed is huge and slow and really should not blog the page.
> [Zola] Add lazyloading arguments for youtube embeds

- .github/workflows/build-matrix.org.yml
This is a thing we do on Synapse, and it makes things build faster by not tying up GHA workers with builds we don't care about.
Preview: https://pr1510--matrix-org-previews.netlify.app
> Cancel concurrent GHA builds

- gatsby/content/blog/2022/11/2022-11-22-synapse-1.72.mdx
Preview: https://pr1572--matrix-org-previews.netlify.app
> Add blog post for Synapse 1.72/71/70

- gatsby/content/blog/2022/12/2022-12-01-foundation-membership.mdx
This PR fixes a malformed link (relative to absolute) to the GitHub matrix.org project.
> Fix malformed link

- content/docs/legacy/_index.md
- templates/docs/legacy_index.html
Note:
- Docs are in no special order, but I don't think that's a big deal since they are legacy docs
- There are no subsection, everything under `legacy` is a page
> List all docs under the legacy section

- gatsby/src/pages/security-disclosure-policy.js
This PR adds an explanation about a configuration which could be confused as a low criticality security issue.
> Add note about directory listing by design

- README.md
So that we don't have to perform archaeology to find this information out every time.
Preview: https://pr1609--matrix-org-previews.netlify.app
> Add information on how matrix.org is deployed to README

- gatsby/content/blog/2023/02/2023-02-10-twim.mdx
Queued this up but forgot to hit send. Considering it contains news about a Matrix spec release that's coming in the next 4 days - we should make sure it gets out.
> Add missing spec section to 2023-02-10 TWIM

- gatsby/content/blog/2023/02/2023-02-24-twim.mdx
This is a somewhat experimental proposal.
I started doing these transcriptions and thought it might make sense to add them directly in the TWIM edition the video is featured in instead of a week later as a post. Feel free to suggest changes or to reject it if this is unwanted :)
Preview: https://pr1670--matrix-org-previews.netlify.app
> Add link to the community made transcription of the video in TWIM

- gatsby/content/blog/2023/02/2023-02-28-synapse-1.78.mdx
Preview: https://pr1675--matrix-org-previews.netlify.app
> Blog post for Synapse 1.78

- gatsby/content/blog/2023/03/2023-03-03-twim.mdx
MSC3887 was incorrectly marked as *Accepted*, when in reality it had been *Closed*.
> Fix description of MSC3887 in TWIM 2023-03-03

- sass/_blog.scss
Otherwise, they won't scale correctly.
This is a regression. We seem to have lost this CSS line somewhere in the past.
Fixes #1748
> [zola] Make sure that the iframes are in the 16/9 aspect ratio. 

- sass/_base.scss
If the content doesn't otherwise fill the viewport, make it expand so the footer is at the very bottom of the viewport.
| Before | After |
| ------ | ----- |
| ![Screenshot 2023-05-09 at 12-37-13 Matrix org - Podcasts](https://github.com/matrix-org/matrix.org/assets/951129/35e94357-90fb-445e-886c-5f1d9fb36798) | ![Screenshot 2023-05-09 at 12-38-14 🛠️ Matrix org - Podcasts](https://github.com/matrix-org/matrix.org/assets/951129/b27c6cf9-0b02-45a3-bfee-91c83eb32007) |
> Make sure the footer sticks to the bottom

- .github/CODEOWNERS
After seeing it work with synapse-core, it seems like a nice addition, especially given the upcoming RACI matrix for the security process.
Alternatively we could also have it include `*vulnerabilit*` and/or `*advisor*`, but checking historical blog posts, most of the security-related ones have `security` in their title.
Preview: https://pr1809--matrix-org-previews.netlify.app
> Set @matrix-org/security as CODEOWNERS for security blog posts

- templates/ecosystem/clients.html
Obsolete clients as default is not visible .I have removed checked attribute from obsolete filter option.
> Don't show obsolete clients as default

- content/blog/2018/05/2018-05-08-gdpr-compliance-in-matrix.md
Based on https://matrix.to/#/!kOXQjUbOfdYNCtRmZv:matrix.org/$CLx_sMq2x-9etx-KSv2-brn-ojcwDRHvsvfsjVoFalo?via=matrix.org&via=element.io&via=envs.net
This makes sense as an exception since this article is mentioned in a recent MSC.
Changes are:
- Whitespace fixes
- HTML to markdown converted
- SmartQuotes removed
- Removed unnecessary linebreaks that caused extra spaces
- Add some (inline) codeblocks to improve readability
> Improve typesetting of 2018-05-08-gdpr-compliance-in-matrix.md

- config.toml
Reduce the `search_index.en.js` file, it is 36.8 MB in size and takes >8s to build. This is too big to deploy on cloudflare pages.
This change reduces it to 2.7M (arguably still too big) and builds in <2s
We should look at the [search](https://www.getzola.org/documentation/getting-started/configuration/#:~:text=paths_keep_dates%20%3D%20false-,%5Bsearch%5D,-%23%20Whether%20to%20include) configuration in greater detail. Using a value of `100` and/or excluding the content would be ideal
> Reduce index size

- config.toml
Update the `base_url` as this redirects parts of the site to elsewhere which makes testing tricky.
For now, the `CF_PAGES_URL` is used to override this, and before deployment we'll set that only for non `main` deployments; those will use this setting (matrix.org)
> Zola base url

- sass/_base.scss
Added highlight to social media icons.I have added the CSS code filter: brightness(0) invert(1); to the img:hover selector inside the a selector, which will invert the colors of the image, effectively making it white, when the image is hovered over.
> Add highlighting to social media icons #1779

- static/_headers
- static/_redirects
Converts the `header set` and `rewriterule` configuration from our apache config to cloudflares `_headers` and `_redirects` files :crossed_fingers:
> Zola headers and redirects

- build.sh
Add a build script because
1. We want to use the zola config for production builds
2. We want to deploy a staging instance to test on
3. All other builds should work on cf pages without broken links
> Build script for zola

- static/_redirects
Fixes `/latest.html` paths such as:
https://zola-fixup-spec-redirects.matrix-website.pages.dev/docs/spec/client_server/latest.html
https://zola-fixup-spec-redirects.matrix-website.pages.dev/docs/spec/server_server/latest.html
> Fix .html path

- content/ecosystem/clients/fractal.md
This address doesn't exist and it's not the canonical alias of the room anyway :slightly_smiling_face:.
> Fix Fractal's room address

- static/_redirects
Change the order, because:
https://matrix.org/docs/spec/rooms/#feature-matrix
goes to
https://spec.matrix.org/rooms/#feature-matrix
instead of
https://spec.matrix.org/latest/rooms/#feature-matrix
> First match wins

- static/_redirects
Fixes https://github.com/matrix-org/matrix.org/issues/1879
```
$ curl -sIL https://7ab1dba5.matrix-website.pages.dev/docs/spec/push_gateway/r0.1.0.html|grep -E "location|HTTP"
HTTP/2 302 
location: https://spec.matrix.org/legacy/push_gateway/r0.1.0.html
HTTP/2 200 
$ curl -sIL https://7ab1dba5.matrix-website.pages.dev/docs/spec/server_server/r0.1.0.html|grep -E "location|HTTP"
HTTP/2 302 
location: https://spec.matrix.org/legacy/server_server/r0.1.0.html
HTTP/2 200 
```
> Fix legacy redirects

- templates/atom.xml
- templates/rss.xml
Fixes #1868 by overriding `atom.xml` and `rss.xml` default templates (default templates are in https://github.com/getzola/zola/tree/master/components/templates/src/builtins)
> Display the full content of the article in the RSS feed

- content/ecosystem/clients/fluffychat.md
Update URL so the "Use in Your Browser" really leads to the webapp.
(as mentioned in #1845)
> [Clients / FluffyChat] Fix Link

- content/ecosystem/clients/neochat.md
The Flathub-Link on the Client-Page for NeoChat is currently broken because the app id is wrong.
This change fixes this, so that the Link on the Client-Page does not result in a 404.
Currently: [org.kde.NeoChat](https://flathub.org/apps/org.kde.NeoChat)
Fixed: [org.kde.neochat](https://flathub.org/apps/org.kde.neochat)
> [Clients / NeoChat] Fix flathub.app_id

- content/blog/2017/05/2017-05-18-synapse-0-21-0-is-released.md
- content/blog/2017/07/2017-07-06-synapse-0-22-0-released.md
- content/blog/2017/08/2017-08-30-pr.md
- content/blog/2018/05/2018-05-25-gdpr-on-matrix-org.md
- content/blog/2018/05/2018-05-29-matrix-org-homeserver-privacy-policy-and-terms-of-use-being-enforced-today.md
- content/blog/2019/04/2019-04-26-this-week-in-matrix-2019-04-26.md
- content/blog/2021/09/2021-09-10-pre-disclosure-upcoming-critical-fix-for-several-popular-matrix-clients.md
- content/blog/2021/09/2021-09-13-vulnerability-disclosure-key-sharing.md
- content/blog/2021/11/2021-11-18-pre-disclosure-upcoming-security-release-of-synapse-1-47-1.md
- content/blog/2021/12/2021-12-03-pre-disclosure-upcoming-security-release-of-libolm-and-matrix-js-sdk.md
- content/blog/2021/12/2021-12-13-disclosure-buffer-overflow-in-libolm-and-matrix-js-sdk.md
- content/blog/2021/12/2021-12-15-on-matrix-and-the-log4j-vulnerabilities.md
- content/blog/2022/01/2022-01-31-high-severity-vulnerability-in-element-desktop-1-9-6-and-earlier.md
- content/blog/2022/08/2022-08-05-this-week-in-matrix-2022-08-05.md
- content/blog/2022/08/2022-08-12-this-week-in-matrix-2022-08-12.md
- content/blog/2022/08/2022-08-31-security-releases-matrix-js-sdk-19-4-0-and-matrix-react-sdk-3-53-0.md
- content/blog/2022/09/2022-09-13-security-release-of-matrix-appservice-irc-0-35-0-high-severity.md
- content/blog/2022/09/2022-09-23-pre-disclosure-upcoming-critical-security-release-of-matrix-sd-ks-and-clients.md
- content/blog/2022/12/2022-12-16-this-week-in-matrix-2022-12-16.md
- content/blog/2022/12/2022-12-23-this-week-in-matrix-2022-12-23.md
- content/blog/2023/02/2023-02-03-this-week-in-matrix-2023-02-03.md
- content/blog/2023/03/2023-03-28-security-releases-matrix-js-sdk-24-0-0-and-matrix-react-sdk-3-69-0.md
- content/blog/2023/05/2023-05-19-this-week-in-matrix-2023-05-19.md
- content/blog/2023/05/2023-05-24-disclosing-synapse-security-advisories.md
- content/blog/2023/05/2023-05-26-this-week-in-matrix-2023-05-26.md
- content/blog/2023/06/2023-06-20-membership-program.md
- content/blog/2023/07/2023-07-04-what-happened-with-the-archive.md
- content/blog/2023/07/2023-07-14-twim.md
- content/blog/2023/07/2023-07-18-a-giant-leap-with-mls.md
There were some author names duplicated or merged into a single string. This commit fixes that.
Based on the overview at https://matrix.org/author/
> Fix: Unify author names which were unusual or duplicated

- content/blog/2023/07/2023-07-04-what-happened-with-the-archive.md
Minor fixes for the Matrix Public Archive post. Mostly just fixing the markdown.
> Minor fixes for the Matrix Public Archive post

- static/_redirects
Move rule and attempt to make it more obvious static rules shouldn't go below dynamic ones.
Why CF don't allow 2 files I cannot say.
> CF issues a warning about ordering

- content/ecosystem/sdks/sdks.toml
This change adds https://github.com/Cosium/matrix-communication-client to the ecosystem page.
> Add Cosium/matrix-communication-client to the ecosystem page

- README.md
https://getzola.org/ does not resolve; however https://www.getzola.org/ works.
> Update zola url

- templates/atom.xml
- templates/macros/atom.html
> Limit the RSS feed to 15 entries

- content/ecosystem/sdks/sdks.toml
It isn't a proper SDK, its just element-web guts with a poor name
> Remove matrix-react-sdk

- content/ecosystem/bridges/email/bridges.toml
https://etke.cc/help/bridges/postmoogle is a quick start guide for etke.cc customers, using configuration patterns specific to etke.cc. The actual bridge documentation is in the README.md file and docs/ dir within the bridge repo
> fix postmoogle docs link

- content/ecosystem/integrations/integrations.toml
Honoroit is a helpdesk bot we've developed, currently we use it for etke.cc customer support
https://gitlab.com/etke.cc/honoroit
> Add Honoroit to integrations

- content/blog/2023/10/2023-10-06-twim.md
- content/blog/2023/10/2023-10-13-twim.md
Some of these spec updates are real long, I'd prefer the separator to be after Matrix live (or maybe the first heading? a bit weird), but have put it after the spec updates for consistency.
> Add missing <!-- more --> separators to latest two articles

- templates/post.html
This removes a small warning which google has in their validator. And since we now do images on posts this is a simple fix.
> Ensure we add images to the NewArticle metadata

- content/ecosystem/clients/neochat.md
The client has gained support for spaces. It is unknown to me when did that happen, as it is not mentioned in the changelog.
I have also updated the date of last release according to [the app's website](https://apps.kde.org/neochat/).
> Update NeoChat client description

- content/ecosystem/bridges/mattermost/bridges.toml
I guess matrix-as-mm should also be mentioned in the list of mattermost appservice bridges
> More advanced fork of mattermost appservice bridge is added

- static/js/components.js
As a user, I open a link to the latest twim report from #twim:matrix.org to read it. Then, I want to watch the video but I don't want to allow youtube cookies on matrix.org.
Add an "Open in Youtube" button to the video's placeholder so I can quickly navigate to the video in a new tab.
> Add open in youtube button in video placeholder

- content/docs/older/stateres-v2.md
This just fixes a misplaced space I noticed while using the doc to implement stateres :)
> Fix a missplaced space

- content/ecosystem/clients/cinny.md
- content/ecosystem/clients/commet.md
- content/ecosystem/clients/element-x.md
- content/ecosystem/clients/element.md
- content/ecosystem/clients/fluffychat.md
- content/ecosystem/clients/fractal.md
- content/ecosystem/clients/gomuks.md
- content/ecosystem/clients/gotktrix.md
- content/ecosystem/clients/hydrogen.md
- content/ecosystem/clients/iamb.md
- content/ecosystem/clients/kazv.md
- content/ecosystem/clients/matrix-commander.md
- content/ecosystem/clients/mnotify.md
- content/ecosystem/clients/neochat.md
- content/ecosystem/clients/nheko.md
- content/ecosystem/clients/quadrix.md
- content/ecosystem/clients/quaternion.md
- content/ecosystem/clients/schildichat.md
- content/ecosystem/clients/syphon.md
- content/ecosystem/clients/thunderbird.md
- content/ecosystem/clients/watch-the-matrix.md
Considering this feature is not even in the spec and only 3 out of 21 listed clients implement it, I don’t think it’s fair to have it in the list. We could do with one less unticked box on the page.
I only touched “my” client so far, but I can amend the PR to remove it from all the non-supporting ones if deemed appropriate. What do you reckon?
Of course, considering the page dynamically picks up whatever feature is listed in the Markdown file, clients that do implement widgets can keep the feature listed!
> Stop advertising lack of widget support

- templates/post.html
- templates/skel.html
Changes the snippet to track custom events, needed according to https://plausible.io/docs/custom-event-goals#1-change-the-plausible-snippet-on-your-site
Adds the class name to track the CTA on the blog posts specifically, using the format specified in https://plausible.io/docs/custom-event-goals#you-can-also-add-class-names-directly-in-html
> Track blog posts CTA

- sass/_support.scss
> Add spacing and alignment on mobile to the Supporters page

- content/ecosystem/sdks/sdks.toml
Fixes https://fosstodon.org/@lil5/111940191501771658
> fix: update maturity level of gomatrix SDK to "Obsolete"

- sass/_index.scss
In classical graphical design you almost never center something to literally 50% of the height of the screen; instead you aim for the golden ratio of 0.618:1 rather than 1:1.  I've tweaked this a bit more to account for the visual density of the logo & accompanying text.  Closes https://github.com/matrix-org/matrix.org/issues/1836
> Fix vertical centering of the matrix logo on matrix.org

- static/.well-known/matrix/support
The "admin" contact is largely meant to be used for reporting users and such, so we supply our abuse contact there.
> Add MSC1929 support contacts

- content/about/guardians.toml
- content/about/index.md
Adding context to make sure we're being forthright and transparent about staff working arrangements (eg, most are seconded through Element).
> minor fixes + transparency in staff arrangements

- content/blog/2024/03/2024-03-01-twim.md
removing unnecessary escape characters that broke links
> fix broken links in kazv report

- content/ecosystem/integrations/integrations.toml
pipe2matrix is a program/bot that redirects input/output of another program into a matrix room. This PR adds pipe2matrix to the list on the ecosystem/integrations webpage.
> integrations.toml: add an integration "pipe2matrix" to the list.

- sass/_support.scss
> Improve the padding around the member images

- static/assets/rss.svg
Fixes padding on the icon introduced in #2287
> Remove padding of rss icon

- content/about/staff.toml
- content/contact.md
- templates/shortcodes/staff.html
added support for including staff email addresses, and added my own email address. also mentioning on the contact page that some more contact details are available in the about section.
> add contact info for Josh

- templates/membership.html
putting community first, and foundation last, and aligning the sorting of foundation rep listing with the rest of the listings
> reorder display of Governing Board composition

- sass/_header.scss
The menu section is 47.5px tall, so the submenu wrap should have the same value in order to align it and not have the submenu disappear when transitioning from the menu to the submenu area.
Fixes #2278 and replaces #2267
> Adjust section submenu wrap top to match the menu height

- content/ecosystem/sdks/sdks.toml
Add Elm SDK as a beta SDK to the configuration listing all ecosystem SDKs.
> Add Elm SDK to SDK ecosystem

- content/blog/2024/04/2024-04-26-twim.md
Oops, I forgot to TWIM this week. I am a bad person.
This announces the latest Synapse security release, so should probably go in.
> Add Synapse update to TWIM 2024-04-26

- sass/_elections.scss
- templates/governing-board/elections.html
- templates/macros/nominee.html
This does a few things:
- Sort the member types to match the above text for easier reading flow
- Add the maximum possible seats to the title to avoid having to scroll up as often
- Make the members look like headers (semantically they aren't, but visually it makes it easier to follow together with the next change)
- Add headers instead of a list to each member to make clear which part refers to what
> Improve the Nominee Page

- content/ecosystem/servers/servers.toml
Conduwuit is a hard-fork of conduit, so is worthwhile listing as a separate homeserver. Adds the repository for jSynapse, which was missing.
> Add conduwuit and repo for jSynapse to servers metadata

- templates/try-matrix.html
On https://matrix.org/try-matrix/:
> We recommend Element as a safe default, but there is a variety of clients available.
`clients` is plural, so the verb `is` should be `are` instead.
> Fix minor grammatical error

- content/blog/2024/05/2024-05-03-twim.md
these were not recognizable as being links when styled as h4. maybe the `h4 a` css needs a fixin too?
> Fix link formatting issue 2024-05-03-twim.md

- content/governing-board/elections/2024/index.md
In the voting section `Voting has begun` points to `/blog/2024/05/17/voting-begins`. I assumed that the desired page could be `/blog/2024/05/voting-begins`.
> Fixed "voting has begun" broken link

- sass/_header.scss
Previously, the button would touch the bottom of the `nav` container, which looked a bit off IMO.
|Before|After
|---|---|
|![Screen Shot 2024-05-22 at 22 00 17](https://github.com/matrix-org/matrix.org/assets/6900601/83703fec-39d1-4604-80d0-4b42356aa821)|![Screen Shot 2024-05-22 at 21 59 20](https://github.com/matrix-org/matrix.org/assets/6900601/573f8082-32ec-467a-941d-a0ec99a063ed)|
> Add spacing below "Try Matrix" button in phone nav

- content/security-disclosure-policy.md
Make the time to reply a clear commitment and spell out the hall of fame crediting in the process.
> Update response time and clarify HoF crediting

- content/ecosystem/clients/nheko.md
It's a shame that Cinny, which doesn't support a lot of stuff is listed in "featured" while much more advanced and feature-complete Nheko is somewhere below. Moreover, Nheko is Qt/C++ based client, which makes it faster as a native application and more suitable for older hardware (and there are lot of people with less beefy hardware out there). Since Nheko just recently made a release, I propose moving it to a "Featured" section.
https://github.com/Nheko-Reborn/nheko/releases/tag/v0.12.0
For example, Cinny doesn't support VoIP, Threads, and multi-language, while Nheko does.
Closes https://github.com/matrix-org/matrix.org/issues/2394
> Nheko: mark as featured client

- sass/_base.scss
It shouldn't be possible for the contents of page headers to overflow, considering the page header is bound by a variable sized bounding box (i.e., `min-height` instead of `height`).
I think it's dangerous to have `overflow: hidden` without reason, as if the design's implementation were to change, we would could be cutting off content without realising it.
> Remove `overflow: hidden` on page headers

- content/ecosystem/clients/nheko.md
Using the old flathub id would be very confusing. And while it is sad, mujx hasn't been a maintainer for a while. They certainly started the project and did a humongous of work, but I think maintainers should probably reflect current contacts at this point?
The room change is mostly a visual thing. It points to the same room, but we usually use the nheko.im one and it is the canonical alias, so it probably is better to document that this way as well.
> Update Nheko information

- config.toml
resolves #2422
there is also a transitional period of the config field with zola 0.19.1 https://github.com/getzola/zola/blob/master/CHANGELOG.md
> Fix feeds generation config for zola 0.18

- content/ecosystem/sdks/sdks.toml
Hello,
I wrote a C# library for working with matrix as a semester project for uni and I'd like to publish it to the list of SDKs.
Signed-off-by: Greenscreener <gs@grsc.cz>
> Add matrix_dotnet to the list of SDKs

- content/ecosystem/clients/kazv.md
With https://iron.lily-is.land/D120 kazv supports multi-accounts. Also v0.5.0 is [released](https://lily-is.land/kazv/kazv/-/releases/v0.5.0) on Aug 3, 2024.
> Update info on kazv

- content/legal/code-of-conduct.md
The mjolnir that is used to protect the rooms covered under the matrix.org COC is as far as the community can tell the `@abuse:matrix.org` bot. The `@administrator:matrix.org` account doesnt even have a profile that i can lookup on feline.support meanwhile the `@abuse:matrix.org` account has a profile and its the profile we all know.
Signed-off-by: Catalan Lover <catalanlover@protonmail.com>
> Correct the MXID of the matrix.org mjolnir

- content/security-disclosure-policy.md
Given how the industry has moved on from calling it "responsible" disclosure and even the wikipedia page has been renamed (https://en.wikipedia.org/wiki/Responsible_disclosure redirects to https://en.wikipedia.org/wiki/Coordinated_vulnerability_disclosure), I think it makes sense to switch this on the Matrix website too.
> Rename responsible disclosure to CVD

- content/security-hall-of-fame/findings.toml
> Add entries to Security Hall of Fame

- static/.well-known/element/element.json
Add element wellknown for registration_helper_url
> Add element wellknown for registration_helper_url

- content/docs/matrix-concepts/rooms_and_events/_index.md
before:
this PR fixes a text discrepancy to the image.
> adapt text to image info (room_join.svg)

- README.md
Using `--filter=blob:none` offers a smaller download size while not having a shallow clone in the end. This should reduce the issue of the size of the repository.
See https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/ and https://nayak.io/posts/git-clone-optimizations/ for the technical details.
Repo size without:
```
❯ git count-objects -vH
count: 0
size: 0 Bytes
in-pack: 69431
packs: 2
size-pack: 1.18 GiB
prune-packable: 0
garbage: 0
size-garbage: 0 Bytes
```
Reposize after:
```
❯ git count-objects -vH
count: 0
size: 0 Bytes
in-pack: 46580
packs: 2
size-pack: 612.00 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 Bytes
```
a gc does _not_ help us here as it would be only local.
This does have the tradeoff of slower git blame. But I hope this is …
> Suggest smarter cloning

- content/ecosystem/servers/servers.toml
Dendrite is outside the foundation :cry:
License should be `AGPL-3.0-only OR LicenseRef-Element-Commercial`, but the second part in SPDX may be unreadable, so it is `Element Commercial License`
> Update for Dendrite

- content/ecosystem/servers/servers.toml
The old alias is inaccessible.
The telodendria room in the servers subspace (https://matrix.to/#/!JxVdjluQhAiplXpUpi:t2l.io?via=matrix.org&via=envs.net&via=tchncs.de) of Matrix Community will tell you the room ID !ykbwcwqRyRJhteUiDp:bancino.net which you can try to guess some vias for to join, e.g. https://matrix.to/#/!ykbwcwqRyRJhteUiDp:bancino.net?via=matrix.org&via=t2l.io. Once in, the room announces #general:synapse.telodendria.io as its canonical alias.
Calling @jordanbancino to confirm :)
> Update telodendria room alias

- content/ecosystem/sdks/sdks.toml
To better reflect the maturity of the SDK to help new client developers parse the SDK ecosystem.
cc @poljar
> update rust-sdk maturity from beta to stable

- static/.well-known/matrix/client
Meanwhile matrix.org has its own instance of the jwt-service. This PR is updating the URL
> update jwt service URL to the matrix.org instance

- content/ecosystem/hosting/providers.toml
I have added the year since Ossrox is operating. (I am one of the managing directors.)
> Added operating_since value for Ossrox

- CONTENT.md
- CONTRIBUTING.md
> Update repository instructions

- static/_headers
Adds cross-origin headers to well-known records to support looking up support info and future records.
This change also includes the `server` record, as it's useful in the context of LibMatrix/RMU to correctly address a server when looking up implementation type (which enables some implementation-specific optimisations and features).
I can downgrade this to only cover client and support records if wanted.
> Fix well known CORS to allow looking up support info from browser clients

- content/ecosystem/bridges/discord/bridges.toml
> Update Out Of Your Element feature set

- content/ecosystem/bridges/email/bridges.toml
Postmoogle has been moved to GitHub, I've updated repo and docs link in consequence.
> fix postmoogle repo and docs (moved to github)

- templates/includes/header.html
the iterator variable `page` nameclashed with the page variable of the current page (https://www.getzola.org/documentation/templates/pages-sections/#page-variables: "Whichever template you decide to render, you will get a page variable in your template [...]"), which means from a page with the navigation disabled you would override the other individual pages' setting.
This led to the following bug on the elections page:
> fix nameclash in navbar template page variable

- content/ecosystem/bridges/groupme/bridges.toml
- content/ecosystem/bridges/slack/bridges.toml
Resolves #2579
Supersedes #2621
Seems like we didn't have a lot of them on the page in the first place https://github.com/spantaleev/matrix-docker-ansible-deploy?tab=readme-ov-file#bridges
> mark mx-puppet-bridges as obsolete

- content/foundation/governing-board/bylaws/02-bylaws.md
- content/foundation/governing-board/bylaws/03-social-contract.md
- content/foundation/governing-board/bylaws/04-processes.md
- content/foundation/governing-board/index.md
When I created #2740 I accidentally used the initial version I proposed to the Board, rather than the version we approved in the meeting. There were a number of minor differences that had been proposed & accepted internally that got missed as a result.
I went though and diffed the internal version with this repo, and made the necessary changes. This PR brings the published doc back to the the approved version, as it *should* have been the first time.
As these are minor edits, I've bumped the version to 1.0.1, following something semver-ish :)
cc @HarHarLinks
> Update to v1.0.1 of the GB bylaws

- sass/_index.scss
- templates/index.html
supersedes #2732
- see individual commits
- reasoning for the horizontal position of the visualisations
- place image responsively at 20% within viewport (this is done by feeling, it ignores the exact image width etc)
- keep it within 600px from the center (content width)
- keep it at least 300px from the center (leave space for the text and buttons)
> Fix visualisation positioning on homepage

- templates/macros/supporters.html
- templates/support.html
Solves Issue (#2756 )
This PR updates the Tera template to sort Foundation members alphabetically by name within each tier (Platinum, Gold, Silver, etc.) during rendering. The supporters.toml file remains unchanged.
Thank you for the clarification! I've implemented the sorting directly in the Tera template as suggested. Let me know if any changes are needed.
> Sort foundation members alphabetically in display

- static/.well-known/matrix/client
Turns out, some clients (like Element iOS and Android legacy) still use the old way of discovering MAS for linking some account management features, and we forgot to update the well-known when we deployed MAS on matrix.org.
> Advertise MAS through the old MSC2965 discovery mechanism

- static/.well-known/element/element.json
Per the removal deadline set by https://github.com/matrix-org/matrix.org/pull/2494#issuecomment-2355235778, I assume this helper can and should have been removed as matrix.org migrated to MAS.
@ara4n could you please merge or provide an update if that's not yet possible? :)
> Remove element wellknown for registration_helper_url

- content/blog/2025/05/2025-05-30-twim.md
Official documentation says 4 days, 31st to 3rd.
> Fix date for 2025 Matrix Community Summit

- navigation.toml
Resolves #2793 
This PR adds a separate "Law Enforcement Guidelines" link to the site footer to provide direct access to the law enforcement guidelines
> Add Law Enforcement Guidelines Link to Footer 

- content/ecosystem/sdks/sdks.toml
See https://github.com/matrix-org/matrix-rust-sdk/pull/5341 and https://github.com/matrix-org/matrix-js-sdk/pull/4901
> make link between Element and the rust+js sdks clear

- CONTENT.md
- templates/shortcodes/figure.html
🎩 Website & Content WG
I have been advised that it is counter productive to double up alt and caption as screen readers will already read the caption anyway. This PR gives us the option to add alt in cases where we don't want to include a caption.
> fix a11y of the figure shortcode

- content/contact.md
- content/homeserver/_index.md
- content/homeserver/about.md
- content/homeserver/official.md
- content/homeserver/pricing.md
- navigation.toml
- sass/_header.scss
- templates/includes/header.html
- templates/shortcodes/notice_box.md
- templates/try-matrix.html
This PR integrates the loose pages with info about the matrix.org homeserver added in #2787 and #2805 into a proper section on the website.
Timeline: merge before 2025-07-21 for the m.org premium account rollout.
> Add homeserver section

- content/foundation/governing-board/index.md
- sass/_governing-board.scss
This PR improves the visual presentation and responsiveness of the Governing Board page by implementing a modern card-based layout system.
fixes #2741 
1. **Representatives Section**
- Implemented a flexible card layout for elected representatives
- Organized cards into distinct category groups (Community, Funder, Foundation)
- Cards display in a single row on larger screens with equal width distribution
- Added subtle visual hierarchy with gradient backgrounds and clean borders
- Improved readability with consistent typography and spacing
3. **Chairs Section**
- Created distinct styling for Governing Board chair vs committee chairs
- Maintained visual consistency while differentiating hierarchy
- Applied gradient backgrounds to individual chair cards
- Added subtle separators between …
> Enhance UI: Implement responsive card layout for Governing Board representatives and chairs (Resolves #2741)
