matrix-org/matrix.org

jekyll/_posts/projects/2016-02-05-try-matrix-now.md
Signed-off-by: Andrew Conrad <aconrad103@gmail.com>
=> Update GitHub repo to matrix-org/matrix.org

jekyll/_posts/projects/2017-11-10-matrix-media-repo.md, jekyll/_posts/projects/2018-03-02-matrix-appservice-iot-proxy.md
Both of these are my projects, so it's probably about time I actually add them.
Closes https://github.com/matrix-org/matrix.org/issues/77
=> Add matrix-appservice-iot-proxy and matrix-media-repo

jekyll/_posts/guides/2015-08-21-application_services.md
=> Fix typo of application services

jekyll/_posts/projects/2016-02-05-try-matrix-now.md, jekyll/_posts/projects/template.md
Fixes #118: Should there be a "bot" category for Matrix projects?
=> Add 'bot' category to projects templates

jekyll/_posts/projects/2014-09-10-neb.md, jekyll/_posts/projects/2014-12-10-ivar2-matrix-irc-bot.md, jekyll/_posts/projects/2015-12-04-hubot-matrix.md, jekyll/_posts/projects/2016-02-03-feedbot.md, jekyll/_posts/projects/2016-03-19-mpd-dj.md, jekyll/_posts/projects/2016-07-29-go-neb.md, jekyll/_posts/projects/2016-09-04-hello-matrix-bot.md, jekyll/_posts/projects/2016-10-30-mxpp.md, jekyll/_posts/projects/2016-12-17-matrix-email-bot.md, jekyll/_posts/projects/2016-12-21-tiny-matrix-bot.md, jekyll/_posts/projects/2016-12-26-matrix-music-bot.md, jekyll/_posts/projects/2017-01-29-rocket-sheep.md, jekyll/_posts/projects/2017-02-05-navi.md, jekyll/_posts/projects/2017-03-19-matrix-voyager-bot.md, jekyll/_posts/projects/2017-05-18-matrix-pollbot.md, jekyll/_posts/projects/2017-06-27-matrix-topic-bot.md, jekyll/_posts/projects/2017-08-21-matterbridge.md, jekyll/_posts/projects/2018-03-08-matrix-mbot.md
Contributes to #118: Should there be a "bot" category for Matrix projects?
=> Categorize all bots as bots

jekyll/_posts/projects/2017-05-02-matrix-knowledge-base.md
FAQBot exists now and code should land soon. Also slight rewordings and better linkification of things.
=> Update Matrix Knowledge Base description

scripts/swagger-ui.patch
=> copy over the patch from matrix-doc repo

unstyled_docs/spec/index.html
Brings in https://github.com/matrix-org/matrix-doc/pull/1440
=> Update index to include the intro

.gitignore, unstyled_docs/spec/intro.html
Fixes https://github.com/matrix-org/matrix-doc/issues/1500
=> Redirect intro.html to index.html

jekyll/_posts/guides/2015-08-21-application_services.md
The indentation in this file caused some pain https://matrix.to/#/!HsxjoYRFsDtWBgDQPh:matrix.org/$1537722418907037aOqoN:matrix.org
=> Fix indentation of application services

jekyll/_posts/guides/2015-08-21-application_services.md
Reverts matrix-org/matrix.org#238
=> Revert "Fix indentation of application services"

jekyll/_posts/guides/2015-08-21-application_services.md
=> Fix application services guide to use kramdown style code blocks

jekyll/_posts/projects/2018-04-24-mini-vector-android.md
according to https://github.com/LiMium/mini-vector-android/blob/limified/README.md#minivector
=> updated some infos

README.md, jekyll/Gemfile, jekyll/Gemfile.lock
As far as I can tell there isn't currently any real instructions on how to build the site
=> Improve first contribution experience slightly

jekyll/_posts/projects/2018-09-05-mxbridge.md
Fixes #226
Any comments/changes @djmaze?
=> Add MxBridge

jekyll/_includes/nav.html
In addition, change the existing home page link to use HTTPS.
Fixes #284.
Signed-off-by: J. Ryan Stinnett <jryans@gmail.com>
=> Fix logo in nav to link to site home page

jekyll/_posts/projects/2018-11-20-bridges.md
The feature list seemed to be missing lots of stuff, and had a few mistakes. I've also swiped some of the feature names from Whatsapp to be more consistent.
=> Update discord feature list

jekyll/_posts/projects/2018-09-13-SimpleMatrix.md
The Repo was moved into a subgroup which broke the screenshot as well as the link to the repo. This fixes that
Signed-Off-By: Marcel Radzio <mtrnord1[at]gmail.com>
=> [SimpleMatrix] Update repo url and screenshot

unstyled_docs/spec/index.html
To pull in all the changes that aren't on matrix.org yet
=> Regenerate index for spec

content/faq/questions/q34.md, content/faq/questions/size-of-state_group_state.md, content/faq/questions/unanswered-questions.md, jekyll/_posts/guides/2015-08-19-faq.md, jekyll/_posts/guides/2016-01-01-index.md, jekyll/_posts/projects/2017-01-27-sygnaler.md, jekyll/examples/application-services.rst, scripts/swagger-ui.patch, unstyled_docs/spec/index.html
As per https://github.com/matrix-org/matrix-doc/blob/master/meta/documentation_style.rst
=> Fix spelling of 'homeserver'

jekyll/_posts/projects/2014-08-12-synapse.md
Signed-off-by: Joseph Nuthalapati <njoseph@thoughtworks.com>
=> Mention that Matrix Synapse is available in FreedomBox

jekyll/_posts/projects/2018-12-13-mxtoot.md
Noticed it could use a touchup while scrolling through the page.
=> Light touches to mxtoot description

jekyll/_posts/projects/2018-04-24-opsdroid-connector.md
=> Update opsdroid description to reflect that the connector is now merged into core

jekyll/_posts/projects/2016-02-05-try-matrix-now.md
Untested but I assume this does the same as https://github.com/matrix-org/matrix.org/commit/ff3a37e7469ac7301df708306b3ab7236f027a96
=> Add Ruby to list of languages to force Matrix Ruby SDK to show up in TMN

jekyll/_posts/projects/2018-09-03-clients-matrix.md
Fractal's repo URL has changed; Fractal also supports
predefined room tags.
=> Update Fractal information on Client Matrix

jekyll/_posts/projects/2016-02-05-try-matrix-now.md
Signed-off-by: Aaron Raimist <aaron@raim.ist>
#404 forgot this
=> Add Dart to the language filter so Pattle shows up

gatsby/src/pages/index.js, gatsby/src/templates/category.js, gatsby/src/templates/post-list.js, gatsby/src/templates/post.js
=> Change date format to the one true format

jekyll/_posts/projects/2017-05-02-matrix-knowledge-base.md, jekyll/_posts/projects/2018-10-23-faqbot.md
Signed-off-by: Aaron Raimist <aaron@raim.ist>
=> Update links to Matrix Knowledge Base

unstyled_docs/spec/r0.0.0/application_service.html, unstyled_docs/spec/r0.0.0/index.html, unstyled_docs/spec/r0.0.0/intro.html, unstyled_docs/spec/r0.0.0/server_server.html, unstyled_docs/spec/r0.0.1/application_service.html, unstyled_docs/spec/r0.0.1/index.html, unstyled_docs/spec/r0.0.1/intro.html, unstyled_docs/spec/r0.0.1/server_server.html
Fixes https://github.com/matrix-org/matrix-doc/issues/1897
=> Add more outdated spec warnings

gatsby/src/components/Footer.js
Signed-off-by: Aaron Raimist <aaron@raim.ist>
=> Fix footer links to GitLab and YouTube

gatsby/blog/2019/06/2019-06-21-twim.mdx
Sorry, late typos fix ( ͡° ͜ʖ ͡°)
=> Fix twim 2019-06-21 aa13q typos

gatsby/src/pages/docs/guides.js
=> Remove Riot color scheme guide

gatsby/blog/2014-09-02/17.mdx, gatsby/blog/2015-01-29/348.mdx, gatsby/blog/2015-01-29/349.mdx, gatsby/blog/2015-01-29/351.mdx, gatsby/blog/2015-01-29/353.mdx, gatsby/blog/2015-01-31/371.mdx, gatsby/blog/2017-03-06/2209.mdx, gatsby/blog/2017-03-06/2210.mdx, gatsby/blog/2017-03-13/2264.mdx, gatsby/blog/2017-03-13/2267.mdx, gatsby/blog/2017-03-13/2268.mdx, gatsby/blog/2017-03-13/2269.mdx, gatsby/blog/2017-03-13/2270.mdx, gatsby/blog/2017-05-18/2565.mdx, gatsby/blog/2018-04-27/3124.mdx, gatsby/blog/2018-09-05/3532.mdx, gatsby/blog/2018-10-02/3612.mdx, gatsby/blog/2018-10-22/3655.mdx, gatsby/blog/2018-10-22/3656.mdx, gatsby/blog/2018-10-26/3677.mdx
=> Remove spurious blog posts which aren't blog posts

gatsby/content/projects/clients/pattle.mdx
=> Make Pattle featured

gatsby/content/projects/2019-07-13-riot-web-server-update.mdx
A simple riot.im web update script that is pretty lightweight and nearly standalone (requires jq). That runs on linux (and probably macos)
=> Add https://github.com/grigruss/Riot-web-server-update

gatsby/content/projects/other/matrix-registration.mdx
=> Added matrix-registration TMN

gatsby/content/projects/other/matrix-utils.mdx
=> Added matrix-utils to TMN

gatsby/content/projects/2019-03-06-matrix-bifrost.mdx
=> Edited the file to the new room as requested.

gatsby/content/projects/clients/matrixcli.mdx
=> Added matrixcli to TMN

gatsby/src/pages/docs/projects/hosting.js
=> Fix title for Hosting page

gatsby/content/docs/free-small-matrix-server.mdx
@benparsons Is docs/ the right place?
=> Add guide for setting up a free home server

unstyled_docs/spec/index.html
Also some other minor change which never made it to matrix.org apparently.
**Please review with https://github.com/matrix-org/matrix-doc/pull/2347**
=> Update spec index.html for Room v5 as the default

gatsby/content/blog/2019/12/2019-12-20-a-twim.mdx
Section at the top for Matrix Live to be added - also needs an `image` field for a twitter image from the vid
=> This Week in Matrix 2019-12-20

gatsby/content/projects/2020-04-13-conduit.mdx
=> Add Conduit

gatsby/content/projects/2015-06-27-quaternion.mdx
I assume this works but the clients matrix doesn't work for me on my local dev build
=> Update clients matrix with Quaternion SSO and room upgrade support

gatsby/content/docs/2020-04-14-stateresv2.mdx
If I'm not wrong, I think that in order for this piece of code to work, an extra indentation is needed.
Btw this article is pure gold :p
=> Fix pseudo-code for Kahn's algorithm

gatsby/src/pages/faq.js
Spotted some missing whitespaces.
Not sure how to guard this against them being removed by a whitespace trim IDE integration.
=> Add missing whitespaces

gatsby/content/projects/2014-06-09-riot.mdx, gatsby/content/projects/2015-04-02-riot-ios.mdx, gatsby/content/projects/2015-06-02-riot-android.mdx, gatsby/content/projects/clients/riotx.mdx, gatsby/src/pages/docs/projects/try-matrix-now.js
Signed-off-by: Aaron Raimist <aaron@raim.ist>
=> Tweaks to Riot Android & iOS TMN and FAQ

gatsby/content/docs/online-events.mdx
* team Matrix -> Team Matrix as the whole thing would be a name
* Starting open and open-source on a lowercase character because they are adjectives
=> Small suggestions for online-events.mdx

gatsby/content/projects/clients/nio.mdx
At least a few more boxes to tick 👍
=> Update Nio details

gatsby/content/blog/2020/04/2020-04-29-msc-categories.mdx
=> s/Matrix.org ecosystem/Matrix ecosystem

gatsby/content/projects/2014-08-12-synapse.mdx
Update Synapse Arch Linux repository maintainer to Johannes Löthberg.
=> Update Synapse Arch Linux repository maintainer

gatsby/content/projects/2017-05-02-nheko.mdx
Not sure, if I should specify, that only some aspects of pushrules are supported (you can mute and unmute rooms, which is like 90% what you use them for, but you can't add custom highlight keywords yet, etc.) Also E2EE works, but no device verification yet.
Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>
=> Reflect recent work in Nhekos feature list

gatsby/src/pages/docs/guides.js
I've been writing a guide for newcomers in French. It describes what is Matrix (with a clear focus on escaping surveillance capitalism) and how to install/register to Riot. It's the front page of https://zinz.dev: my own Synapse instance.
I plan on adding an "how to make friends" section, and to translate the guide in English. I will keep you posted.
Hope it helps!
=> Added my French user introduction guide

gatsby/content/projects/clients/daydream.mdx
Yet another Client I am working on. Hopefully, one that doesn't die as fast as my other clients did :)
=> Add Daydream

gatsby/src/components/Footer.js, gatsby/src/components/Navigation.js
This has upset me for a while.
=> TWIM capitalisation

gatsby/content/projects/2014-06-09-riot.mdx
Add a note for the Nextcloud app version of Riot.
Signed-off-by: Gary Kim <gary@garykim.dev>
=> Add a note for the Riot Nextcloud App

.buildkite/pipeline.yaml
=> Add building the implementation guides to CI

gatsby/content/projects/2017-05-02-nheko.mdx
See description of [Nheko](https://github.com/Nheko-Reborn/nheko) since https://github.com/Nheko-Reborn/nheko/commit/6b16616e3a646a5fe3046434a54f9e673c1c0db6
=> Update Nheko client info

gatsby/content/docs/matrix-js-bot-sdk-intro.mdx
It feels like there's a word missing.. like next *post* or next *article*.
But I like the short version much better, so I'm suggesting that.
=> Wording: In the next in this series -> Next in this series,

gatsby/content/projects/bridges/GoHubsBot.mdx
started to work on this bridge, it was working live for 14 days and for the HOPE hackers on planet earth conference with out a glitch. Still work in project so I label it "alpha" will add images etc in a couple weeks.
=> Add GoHubsbot to bridges for mozilla hubs and matrix

implementation-guides/server/book.toml, implementation-guides/server/src/chapter_1.md, implementation-guides/server/src/intro.md
HomeServer -> Homeserver
Fix github link
Remove dead chapter
=> Misc minor improvements to implementation guides

gatsby/src/pages/security-disclosure-policy.js
Added Pritam Mukherjee, TR_SLimey plus a syntax fix for existing entry
=> Updated HOF

gatsby/content/docs/introduction.mdx
=> Docs: More renaming of Riot to Element

gatsby/src/pages/hosting.js, jekyll/_posts/projects/2018-10-22-hosting.md
=> Hosting - Rename Riot to Element

gatsby/content/docs/free-small-matrix-server.mdx
=> riot -> element

unstyled_docs/spec/index.html
**Review with https://github.com/matrix-org/matrix-doc/pull/2803**
=> Update default room version

gatsby/src/pages/docs/guides.js
I started an introduction in matrix on my German blog. Maybe this is interesting to add to the list of guides for users on matrix.org.
=> added german matrix introduction for users

implementation-guides/application-services/book.toml, implementation-guides/application-services/src/SUMMARY.md, implementation-guides/application-services/src/intro.md, implementation-guides/client/book.toml, implementation-guides/client/src/SUMMARY.md, implementation-guides/client/src/intro.md
As requested by various folk. These are still not linked from anywhere
=> Add empty client and application services books

gatsby/content/projects/clients/mnotify.mdx
This adds my pet matrix cli client to the client list.
=> Add mnotify matrix cli client

gatsby/content/projects/2016-10-07-mm.mdx
I moved the source code from gitlab to a gitea instance a while ago.
Updated the description while I was there.
=> Update mm repo and description

gatsby/content/blog/2020/11/2020-11-18-synapse-1.23-released.mdx
=> Synapase 1.23.0 Release Announcement

gatsby/content/blog/2020/11/2020-11-23-synapse-security-disclosure.mdx, gatsby/src/pages/security-disclosure-policy.js
=> Disclose Synapase CVE-2020-26890

gatsby/src/pages/faq.js
I noticed these issues while reading the FAQ, particularly [this section](https://matrix.org/faq/#what-is-the-difference-between-matrix-and-xmpp%3F).
=> FAQ: expand "db"; add missing spaces

gatsby/content/projects/2020-12-04-neochat.mdx
Sorry, i missed a mistake in the Neochat merge request - my own name is spelled wrong :(
=> Neochat: Fix name

gatsby/content/blog/2020/12/2020-12-07-gitter-now-speaks-matrix.mdx
I entered (my own room) wrong on the first try...
=> Use another room to clarify URL/room mapping

gatsby/content/projects/2020-01-04-native-gitter-bridge.mdx
Fix Gitter bridge feature list formatting: https://matrix.org/bridges/#gitter
Part of https://github.com/matrix-org/matrix.org/issues/903
Follow-up to https://github.com/matrix-org/matrix.org/pull/919 and https://github.com/matrix-org/matrix.org/pull/922
=> Fix Gitter bridge feature list formatting (again)

gatsby/content/blog/2021/01/2021-01-13-synapse-1.25.0-released.mdx
To merge once release has been published.
=> Release Post for Synapase 1.25.0

gatsby/content/projects/bots/tiny-matrix-bot-plus.mdx
thanks for updating the datasheet of the bot
=> updated bot info

gatsby/src/pages/security-disclosure-policy.js
This is related to https://github.com/matrix-org/internal-config/issues/947.
=> Add Michaël to HoF.

gatsby/content/projects/clients/matrix-commander.mdx
please update your datasheets, thank you so much !!!
=> 2 new features, software now fully stable, released

gatsby/src/pages/docs/guides.js
Added link to blog post on how to install Synapse (German)
=> Added guide on how to install Synapse (German)

gatsby/content/projects/2019-06-18-matrix-puppet-groupme.mdx, gatsby/content/projects/2021-01-10-mx-puppet-groupme.mdx
Also mark matrix-puppet-groupme as unmaintained.
=> Add mx-puppet-groupme to bridges

gatsby/content/projects/bridges/mautrix-facebook.mdx, gatsby/content/projects/bridges/mautrix-imessage.mdx, gatsby/content/projects/bridges/mautrix-signal.mdx
=> Add iMessage and update other things

gatsby/content/blog/2021/04/2021-04-22-synapse-1.32.2-released.mdx
=> Release Synapse 1.32.2

gatsby/content/projects/clients/syphon.mdx
I forgot to do this in the original PR
=> Feature Syphon on clients page

gatsby/content/projects/other/server_stats-project.mdx
Adding my 3 in 1 Project :) The linked FAQ is being written while I am making this PR and should be online shortly
=> Add Server_Stats Project

gatsby/content/blog/2021/05/2021-05-21-twim.mdx
Feel free to ignore/remove parts/all of it.
=> Fix a few typos

gatsby/content/blog/2021/06/2021-06-10-low-bandwidth-matrix-tutorial.mdx
=> Add low bandwidth tutorial

gatsby/content/docs/e2ee_cross_signing.mdx
Update the e2ee guide to contain bootstrapping (and hopefully soon online key backup)
=> Update e2ee guide

gatsby/content/blog/2021/06/2021-06-11-twim.mdx
Newlines were getting mangled in output
=> Markdownify list

gatsby/content/blog/2021/06/2021-06-14-adventures-in-fuzzing-libolm.mdx
Reviewed by Matthew out of band.
=> Add libolm fuzzing blog post.

gatsby/src/pages/security-disclosure-policy.js
I'd like to, if possible, change my Hall of Fame entry as I've changed my online nickname. Will reply to this from my old GitHub account to confirm.
=> Change nickname in HoF

gatsby/src/pages/faq.js
Does that do the trick for you @richvdh (re: #1031)?
=> Replace matrix-python-sdk with matrix-nio

gatsby/package.json
This gives us `npm run gatsby -- <arbitrary_gatsby_command>` as pointed out by @MadLittleMods in #1046
=> Add gatsby itself as npm script

gatsby/content/projects/2020-01-04-native-gitter-bridge.mdx
Add demo screenshot of the Gitter bridge
Part of https://github.com/matrix-org/matrix.org/issues/1055
=> Add demo screenshot of the Gitter bridge

gatsby/content/projects/sdks/mytrix.mdx
Add µtrix (MicroPython) library
https://edugit.org/hacknfun/thema-mechatronik/mytrix
=> [projects] Add µtrix (MicroPython) library

.github/workflows/build-matrix.org.yml
… but do it as part of the existing workflow this time.
The code is obviously cleaner than in #1088 as splitting the workflows creates a lot of overhead. We should probably merge **this one**.
Preview: https://pr1089--matrix-org-previews.netlify.app
=> 🚀 Publish PR previews on netlify

gatsby/content/projects/servers/conduit.mdx
https://gitlab.com/famedly/conduit#what-is-the-current-status
=> Update Conduit maturity to beta

gatsby/content/blog/2021/11/2021-11-09-matrix-1.1.mdx
November 9th, 2021
Signed-off-by: Travis Ralston <travisr@matrix.org>
I need a PR preview for sanity checking
Preview: https://pr1111--matrix-org-previews.netlify.app
=> Blog: Matrix 1.1 release

gatsby/content/blog/2019/11/2019-11-08-client-server-r0.0.6-and-identity-r0.3.0.mdx, gatsby/content/blog/2020/05/2020-05-27-room-v6-s2s-r0.1.4-c2s-r0.6.1.mdx, gatsby/content/blog/2021/04/2021-04-15-old-gitter-bridge-eol.mdx, gatsby/content/blog/2021/11/2021-11-09-matrix-1.1.mdx
See commits.
Preview: https://pr1113--matrix-org-previews.netlify.app
=> Touch up some of the spec blog posts

gatsby/static/css/matrix-org.webflow.css
Signed-off-by: Alexandre Franke <alexandre.franke@matrix.org>
Preview: https://pr1114--matrix-org-previews.netlify.app
=> 💄 Add top padding to blog navbar

gatsby/content/blog/2021/11/2021-11-18-synapse-1.47.1-predisclosure.mdx
The netlify deploy failed, I think because the PR description was empty at the time. Otherwise it's available at https://pr1119--matrix-org-previews.netlify.app/blog/posts
=> Pre-disclosure for Synapse 1.47.1

gatsby/content/blog/2021/11/2021-11-18-synapse-1.47.1-predisclosure.mdx
Dummy description so netlify CI step doesn't fall over.
Preview: https://pr1121--matrix-org-previews.netlify.app
=> Update to note the vuln was discovered internally

gatsby/content/blog/2021/11/2021-11-30-synapse-1.48.0-released.mdx
(afranke: Putting a non empty description so the netlify preview link gets added)
Preview: https://pr1130--matrix-org-previews.netlify.app
=> Synapse 1.48.0

gatsby/content/projects/bridges/mautrix-googlechat.mdx, gatsby/content/projects/bridges/mautrix-hangouts.mdx, gatsby/content/projects/bridges/mautrix-imessage.mdx, gatsby/content/projects/bridges/mautrix-instagram.mdx, gatsby/content/projects/bridges/mautrix-signal.mdx, gatsby/content/projects/bridges/mautrix-whatsapp.mdx, gatsby/src/pages/bridges.js, gatsby/static/docs/projects/bridges/images/googlechat-icon.svg, gatsby/static/docs/projects/images/googlechat-icon.svg
.
Preview: https://pr1085--matrix-org-previews.netlify.app
=> Update mautrix things

gatsby/content/projects/sdks/matrix-csharp-sdk.mdx, gatsby/src/pages/sdks.js
Preview: https://pr1155--matrix-org-previews.netlify.app
=> Add new C# SDK

gatsby/content/projects/sdks/simple-matrix-bot-lib.mdx
Preview: https://pr1150--matrix-org-previews.netlify.app
=> Update simplematrixbotlib page to version 2.4.1

gatsby/content/blog/2021/12/2021-12-14-synapse-1.49.0-released.mdx
(placeholder description for gha)
=> Synapse 1.49.0

gatsby/package-lock.json
Not merging this on a Friday. :wink: 
More may come.
Preview: https://pr1159--matrix-org-previews.netlify.app
=> ⬆️ Update gatsby dependencies

gatsby/content/projects/clients/ditto.mdx
The URL is unavailable and no website is mentioned on the linked code repo.
Preview: https://pr1217--matrix-org-previews.netlify.app
=> DittoClient: Remove URL https://dittochat.org/

gatsby/content/blog/2022/01/2022-01-14-twim.mdx
As reported in the TWIM Matrix room by Pope_Rigby.
Preview: https://pr1223--matrix-org-previews.netlify.app
=> Typo: appsrvice -> appservice

gatsby/content/blog/2022/01/2022-01-14-twim.mdx
Preview: https://pr1224--matrix-org-previews.netlify.app
=> Add missing spaces and link to TWIM

gatsby/content/blog/2022/01/2022-01-18-synapse-1.50-released.mdx, gatsby/content/blog/2022/01/2022-01-18-synapse-1.50.0-released.mdx
Preview: https://pr1229--matrix-org-previews.netlify.app
=> Synapse 1.50.0

gatsby/content/blog/2022/01/2022-01-18-synapse-1.50-released.mdx
=> fix link in 2022-01-18-synapse-1.50-released.mdx

gatsby/content/blog/2022/01/2022-01-21-twim.mdx
There were similar typos in the last week's post as well even though the updates were from different people https://github.com/matrix-org/matrix.org/pull/1224. Not sure if they are copying and pasting from the same source or if some other step of putting TWIM together is going wrong but someone should look into that.
=> Fix typos in TWIM

gatsby/content/blog/2022/01/2022-01-30-element-desktop-security-announcement.mdx
Preview: https://pr1245--matrix-org-previews.netlify.app
=> Element Desktop security announcement

rapidoc/index.html
I use the available API in Rapidoc here to tweak the font for improved readability. The weight cannot be changed this way, but I reckon this does the trick.
@turt2live hope that works for you.
Preview: https://pr1241--matrix-org-previews.netlify.app
=> ♿️ Increase playground font size

gatsby/content/blog/2022/02/2022-02-02-matrix-1.2.mdx
just need a PR for CI confidence
=> Matrix 1.2 blog post

gatsby/content/blog/2022/01/2022-02-08-synapse-1.52-released.mdx
Preview: https://pr1259--matrix-org-previews.netlify.app
=> Synapse 1.52

gatsby/content/docs/2022-02-11-map-tile-server.mdx
Preview: https://pr1262--matrix-org-previews.netlify.app
=> Add the map tile server guide

.github/_typos.toml
Preview: https://pr1267--matrix-org-previews.netlify.app
=> Stop triggering the CI on non-typos

gatsby/content/docs/2022-02-11-map-tile-server.mdx
Preview: https://pr1282--matrix-org-previews.netlify.app
=> Link to the additional guide written by julian

gatsby/content/projects/clients/Scylla.mdx, gatsby/content/projects/clients/ditto.mdx, gatsby/content/projects/clients/mini-vector-android.mdx, gatsby/content/projects/clients/pattle.mdx, gatsby/content/projects/clients/seaglass.mdx
Preview: https://pr1286--matrix-org-previews.netlify.app
=> Mark Seaglass, Ditto, Scylla, and miniVector as not actively maintained

gatsby/content/blog/2022/03/2022-03-22-synapse-1.55.mdx
Preview: https://pr1297--matrix-org-previews.netlify.app
=> Mention Synapse 1.55.2 in the latest release announcement

gatsby/content/blog/2022/04/2022-04-05-synapse-1.56.mdx
Preview: https://pr1308--matrix-org-previews.netlify.app
=> Synapse 1.56

gatsby/content/blog/2022/05/2022-05-04-matrix-appservice-irc-security.mdx
Preview: https://pr1325--matrix-org-previews.netlify.app
=> Add advisory references to the IRC bridge vulnerability blog post.

gatsby/src/pages/security-disclosure-policy.js
Preview: https://pr1326--matrix-org-previews.netlify.app
=> Add some Hall of Fame entries.

gatsby/src/pages/faq.js
Preview: https://pr1334--matrix-org-previews.netlify.app
=> Improve "What clients are available?" section

gatsby/content/blog/2022/06/2022-06-17-synapse-1.61.mdx
Purposefully waiting till tomorrow to publish this since today is spec release day.
Preview: https://pr1360--matrix-org-previews.netlify.app
=> Synapse 1.61

gatsby/content/projects/bots/rustix.mdx
Add my matrix bot project, written in rust: rustix
Preview: https://pr1316--matrix-org-previews.netlify.app
=> Add rustix bot project

gatsby/content/blog/2022/07/2022-08-03-synapse-1.64.mdx
Preview: https://pr1395--matrix-org-previews.netlify.app
=> Synapse 1.64

gatsby/content/blog/2022/08/2022-08-15-the-matrix-summer-special.mdx
Preview: https://pr1403--matrix-org-previews.netlify.app
=> Fix thirdroom link Matrix Summer Special

gatsby/content/blog/2022/08/2022-08-17-synapse-1.65.mdx
Preview: https://pr1404--matrix-org-previews.netlify.app
=> Synapse 1.65

gatsby/content/blog/2022/08/2022-08-19-twim.mdx
After folks gave me some juicy news internally.
=> Update TWIM 20220819 with widget clarification

gatsby/content/projects/clients/quadrix.mdx
Fixes #671
Preview: https://pr1410--matrix-org-previews.netlify.app
=> Fix language caps on quadrix project

gatsby/src/components/Footer.js
Preview: https://pr1228--matrix-org-previews.netlify.app
=> Update copyright footer to 2022

gatsby/content/projects/clients/matrix-commander.mdx
Please update our project info on your webpage. Thank you. 
Kind regards!  :heart: and thanks!
Preview: https://pr1343--matrix-org-previews.netlify.app
=> updated project info for matrix-commander

gatsby/content/projects/clients/fluffychat.mdx
hopefully this is the right way to update https://matrix.org/clients-matrix/ there was some missing features also got rid of a couple of platforms that aren't supported anymore
=> update fluffychat features

gatsby/content/projects/bridges/matrix-qq-bridge.mdx
Hi guys, I made a new puppeting bridge for Tencent QQ. Although currently in alpha stage, it is fairly usable.
=> Add matrix-qq-bridge

gatsby/content/blog/2022/09/2022-09-02-synapse-1.66.mdx
Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>
Preview: https://pr1428--matrix-org-previews.netlify.app
=> Amin doesn't have a custom API for themselves

gatsby/content/projects/clients/cinny.mdx
Preview: https://pr1391--matrix-org-previews.netlify.app
=> Cinny is available on desktop platforms

gatsby/src/templates/category.js
Fixes #1352.
I don't know if this is right; I don't know what I'm doing, but I thought it would be better than not trying anything
Preview: https://pr1353--matrix-org-previews.netlify.app
=> Try to hide next link page if current page not full

gatsby/content/blog/2022/09/2022-09-13-synapse-1.67.mdx, gatsby/content/blog/2022/09/2022-09-14-synapse-1.67.mdx
Closes https://github.com/matrix-org/synapse/issues/13744
Preview: https://pr1441--matrix-org-previews.netlify.app
=> Synapse 1.67

gatsby/content/blog/2022/09/2022-09-27-synapse-1.67.mdx
[Rendered](https://github.com/matrix-org/matrix.org/blob/babolivier/synapse1.68/gatsby/content/blog/2022/09/2022-09-27-synapse-1.67.mdx)
=> Synapse 1.68

gatsby/content/projects/bridges/gupshup-matrix.mdx
Preview: https://pr1447--matrix-org-previews.netlify.app
=> Gupshup bridge repository update

gatsby/content/projects/bridges/mautrix-discord.mdx, gatsby/content/projects/bridges/mautrix-googlechat.mdx, gatsby/content/projects/bridges/mautrix-slack.mdx, gatsby/content/projects/bridges/mautrix-whatsapp.mdx
Preview: https://pr1461--matrix-org-previews.netlify.app
=> Update mautrix bridges

gatsby/content/projects/bridges/matrix-qq.mdx
Hi, this is a new double puppeting bridge for tencent qq :)
=> Add matrix-qq bridge

gatsby/content/projects/bridges/matrix-wechat.mdx
Hi, this is a new double puppeting bridge for wechat :)
=> Add matrix-wechat bridge

config.toml, content/blog/2022/09/2022-09-02-synapse-1.66.md, content/blog/2022/09/twim/index.md, templates/blog.html, templates/index.html, templates/post.html, templates/taxonomy_single.html
Followup from https://github.com/matrix-org/matrix.org/pull/1477#discussion_r985816859
=> [Zola] Use singular taxonomies instead of plural forms

.github/_typos.toml, .github/workflows/spell-check.yaml, gatsby/content/blog/2018/04/3024.mdx, gatsby/content/blog/2018/10/3638.mdx, gatsby/content/blog/2020/04/2020-04-09-twim.mdx, gatsby/content/docs/2018-09-21-usage-of-the-matrix-js-sdk.mdx
Some changes for `master` this time 😉 
Preview: https://pr1494--matrix-org-previews.netlify.app
=> Fix some typos

gatsby/content/projects/bridges/linkedin-matrix.mdx
Preview: https://pr1493--matrix-org-previews.netlify.app
=> linkedin-matrix: update the repo URL

gatsby/static/docs/projects/images/matrix-commander-rs.svg
Preview: https://pr1498--matrix-org-previews.netlify.app
=> icon/image for new project matrix-commander-rs

gatsby/content/blog/2022/10/2022-10-11-synapse-1.69.mdx
Preview: https://pr1499--matrix-org-previews.netlify.app
=> Synapse 1.69

content/ecosystem/servers/index.md, content/ecosystem/servers/servers.toml, sass/_servers.scss, sass/style.scss, templates/clients.html, templates/servers.html
=> [Zola] Add server table

sass/_blog.scss
=> Make titles in blockquotes smaller than outer titles

gatsby/content/projects/clients/nio.mdx
Preview: https://pr1563--matrix-org-previews.netlify.app
=> Update clients/Nio metadata

content/docs/developers/_index.md, content/docs/users/_index.md
Left to do:
Out of scope:
- Tutorials (they will never be updated)
- Project specific docs (they will never be updated and could mislead people)
Will be split in another PR:
- An introduction for the page, a general overview of how Matrix works: there are several clients connected to different homeservers, federated together, and they send events.
=> Docs for Developers

content/ecosystem/sdks/index.md, content/ecosystem/sdks/sdks.toml, templates/shortcodes/sdk_table.html
The structure for the SDKs page has been laid out, as well as the data structure.
I still need to import the actual data from current matrix.org
=> Implement the SDKs page

gatsby/content/projects/sdks/MatrixAPI.mdx, gatsby/content/projects/sdks/botkit-matrix.mdx, gatsby/content/projects/sdks/drupal-matrix-api.mdx, gatsby/content/projects/sdks/glitch-in-the-matrix.mdx, gatsby/content/projects/sdks/jmsdk.mdx, gatsby/content/projects/sdks/matrix-dotnet-sdk.mdx, gatsby/content/projects/sdks/matrix-erlang-sdk.mdx, gatsby/content/projects/sdks/matrix-haxe.mdx, gatsby/content/projects/sdks/matrix-sync-java-sdk.mdx, gatsby/content/projects/sdks/matrix.org-android-sdk.mdx, gatsby/content/projects/sdks/matrix.org-as-sdk.mdx, gatsby/content/projects/sdks/matrix.org-js-sdk.mdx, gatsby/content/projects/sdks/matrix.org-python-sdk.mdx, gatsby/content/projects/sdks/matrix.org-react-sdk.mdx, gatsby/content/projects/sdks/mautrix-go.mdx, gatsby/content/projects/sdks/mautrix-python.mdx, gatsby/content/projects/sdks/mytrix.mdx, gatsby/content/projects/sdks/net-async-matrix-perl.mdx, gatsby/content/projects/sdks/newlisp-matrix-client.mdx, gatsby/content/projects/sdks/perl6-matrix-client.mdx, gatsby/content/projects/sdks/quotient.mdx, gatsby/content/projects/sdks/small-bot-matrix.mdx, gatsby/content/projects/sdks/swift-matrix-sdk.mdx
Preview: https://pr1591--matrix-org-previews.netlify.app
=> Straighten the sdks data to make parsers life easier

gatsby/content/blog/2022/12/2022-12-25-matrix-holiday-update.mdx
Preview: https://pr1599--matrix-org-previews.netlify.app
=> Add donorbox link to holiday special blog post

gatsby/static/css/matrix-org.webflow.css
Fixes #1152 
Preview: https://pr1607--matrix-org-previews.netlify.app
=> Fix the scroll behaviour on gatsby morg

gatsby/content/blog/2023/01/2023-01-19-synapse-1.75.mdx
https://pr1612--matrix-org-previews.netlify.app/blog/2023/01/19/synapse-1-75-released
Preview: https://pr1612--matrix-org-previews.netlify.app
=> Add Synapse 1.75 and 1.74 blog post

.github/workflows/netlify.yml
The title says it all.
Preview: https://pr1613--matrix-org-previews.netlify.app
=> Use environment variables for user login and head branch

static/.well-known/matrix/client, static/.well-known/matrix/server
Copies over https://github.com/matrix-org/matrix.org/blob/master/content/.well-known/matrix/
=> [Zola] Migrate well-known files to zola

gatsby/content/projects/clients/chooj.mdx
Preview: https://pr1622--matrix-org-previews.netlify.app
=> change status of the client chooj to early alpha

sass/_header.scss, templates/includes/header.html, templates/macros/util.html
=> Make the menu responsive

gatsby/content/blog/2023/01/2023-01-03-matrix-community-year-in-review.mdx
solves #1605 
Preview: https://pr1633--matrix-org-previews.netlify.app
=> Fixed weird hidden text in blog section titles

gatsby/content/blog/2023/01/2023-01-31-synapse-1.76.mdx
Preview: https://pr1635--matrix-org-previews.netlify.app
=> Add Synapse 1.76 blog post

sass/_index.scss, templates/index.html
We're not adding missing cats, but adding Call To Action buttons on the frontpage. Those new sections are pretty, but their point is to route visitors to the most relevant section following their interest :)
=> Add missing CTAs

unstyled_docs/spec/appendices.html
closes https://github.com/matrix-org/matrix.org/issues/454
Updated title of https://matrix.org/docs/spec/appendices.html from spec_appendices.rst to Appendices
=> Fix: Updated title of appendices.html from spec_appendices.rst to Appendices

.github/CODEOWNERS
No idea if this will work, please check my working
Preview: https://pr1660--matrix-org-previews.netlify.app
=> Mark Synapse blog posts for review by Synapse team

gatsby/content/blog/2023/02/2023-02-16-synapse-1.77.mdx
Preview: https://pr1658--matrix-org-previews.netlify.app
=> Blog post for Synapse 1.77

gatsby/content/blog/2023/02/2023-02-17-twim.mdx
Link chooj when first talking about it - small improvement in TWIM 23-02-18
Preview: https://pr1663--matrix-org-previews.netlify.app
=> Link chooj when first talking about it - small improvement in TWIM 23-02-18

gatsby/src/pages/faq.js
Overrides #1662 
Preview: https://pr1666--matrix-org-previews.netlify.app
=> add joinmatrix.org to faq

gatsby/content/projects/bots/maubot-echo.mdx
Preview: https://pr1671--matrix-org-previews.netlify.app
=> projects/bots/maubot-echo: fix repo url

gatsby/content/projects/clients/chooj.mdx
Preview: https://pr1682--matrix-org-previews.netlify.app
=> Update chooj.mdx: better description

gatsby/content/blog/2023/04/2023-04-28-twim.mdx
Gatsby requires these, while zola MUST not have these. Probably a copy mistake :)
Preview: https://pr1753--matrix-org-previews.netlify.app
=> [Old M.org Twim-Fix] Fix iframe size

sass/_bridges.scss, sass/_projects.scss, templates/ecosystem/bridge_implementations.html
=> Fix the maturity pills for the bridges

gatsby/content/blog/2023/04/2023-04-28-twim.mdx
prior to this, one might think matthew's announcement belongs to the zola rewrite
Preview: https://pr1761--matrix-org-previews.netlify.app
=> Add missing header in 2023-04-28-twim.mdx

sass/_docs.scss, templates/docs/with_menu.html
=> Make the docs menu behave nicely

content/about/index.md, content/blog/_index.md, content/docs/chat_basics/matrix-for-im/_index.md, content/docs/chat_basics/private-group-chat/_index.md, content/docs/chat_basics/public-rooms/_index.md, content/docs/communities/getting-started/_index.md, content/docs/communities/moderation/_index.md, content/docs/communities/switching-providers/_index.md, content/docs/legacy/_index.md, content/docs/matrix-concepts/elements-of-matrix/_index.md, content/docs/matrix-concepts/rooms_and_events/_index.md, content/ecosystem/hosting/index.md, content/podcasts/index.md, content/try-matrix.md, templates/ecosystem/bridges.html, templates/ecosystem/client.html, templates/ecosystem/clients.html, templates/ecosystem/hosting.html, templates/ecosystem/sdks.html, templates/ecosystem/servers.html, templates/index.html, templates/page.html, templates/podcasts.html, templates/section.html
=> Add <meta> descriptions on most pages

templates/blog.html, templates/post.html
=> Display all the authors and categories for a post

sass/_projects.scss, static/js/projects.js, templates/ecosystem/clients.html, templates/macros/sdks.html, templates/shortcodes/all_servers.html
=> Make filters accessible via keyboard navigation

gatsby/content/blog/2023/05/2023-05-25-matrix-1.7.mdx
Preview: https://pr1810--matrix-org-previews.netlify.app
=> Matrix 1.7

build.sh
Use the `base_url` in the config
=> Make prod builds work

templates/try-matrix.html
=> Fix Try Matrix

static/_redirects
`_redirect` wildcards add the `:splat` to the destination, so add these suffixes
=> Add html suffix

content/ecosystem/clients/fractal.md
Most of the features from the develoment version are not available yet on the stable version.
=> Fix Fractal's features

content/docs/chat_basics/matrix-for-im/_index.md
As a regular user, a very "advanced" app sounds a bit intimidating.
I believe what the author here was going for was that Element has the most features of any Matrix client. "Advanced" makes it sound like it's the hardest one for regular people to use.
=> Change description of Element from "advanced" to "fully-featured"

static/_redirects
Adding the html suffix to the spec document redirects
=> Merge staging

content/blog/2016/02/2016-02-10-advanced-synapse-setup-with-let-s-encrypt.md, content/blog/2016/11/2016-11-21-matrix-s-olm-end-to-end-encryption-security-assessment-released-and-implemented-cross-platform-on-riot-at-last.md, content/blog/2018/04/2018-04-26-matrix-and-riot-confirmed-as-the-basis-for-france-s-secure-instant-messenger-app.md, content/blog/2018/10/2018-10-11-the-story-of-giveth-s-new-matrix-chatbot.md, content/blog/2018/10/2018-10-22-modular-the-world-s-first-matrix-homeserver-hosting-provider.md, content/blog/2019/01/2019-01-17-ben-s-favourite-projects-2018.md, content/blog/2020/11/2020-11-03-how-we-fixed-synapse-s-scalability.md, content/blog/2021/07/2021-07-21-germany-s-national-healthcare-system-adopts-matrix.md
=> Add redirect to former URLs lost in migration

static/_redirects
Translated from our apache config. The first iteration was done in something of a hurry.
These are live @ https://staging.matrix.org/ FWIW
=> Update redirect rules

config.toml
=> Add title and description in feeds

content/ecosystem/sdks/sdks.toml
Trixnity already has been stable for a while
=> made Trixnity stable

content/blog/2023/06/2023-06-30-twim.md
We write it with small c now :)
=> Update 2023-06-30-twim.md: Chooj -> chooj

content/blog/2023/07/2023-07-04-deportalling-libera-chat.md
To make the distinction between Matrix and the matrix.org homeserver clear
=> tidy up language

templates/docs/legacy.html
=> Tone down the warning on the legacy docs

templates/macros/clients.html
=> Add linux label to non-flatpak linux clients

content/blog/2023/07/2023-07-21-twim.md
Zola needs those <> around links to work
=> Fix some bare links

static/_redirects
Fixes https://github.com/matrix-org/matrix.org/issues/1955
=> Redirect for categories

content/blog/2023/07/2023-07-28-twim.md
As mentioned in https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$_senBcdFrwb_vpzqv4Hn4k48Xpn6v57XOXnQi5DgO9M?via=matrix.org&via=element.io&via=envs.net
=> TWIM: Fix project links

content/security-hall-of-fame/findings.toml
This corresponds to https://github.com/matrix-org/sydent/security/advisories/GHSA-p6hw-wm59-3g5g.
=> Update HOF for Sydent 2.5.6

content/blog/2023/07/2023-07-31-bridges-security-updates.md
We're still waiting on one, so feel free to wait if you'd rather.
=> Add CVE IDs to bridge sec update blog post

sass/_try-matrix.scss, templates/try-matrix.html
as a temporary measure to #1570
see also #1853
=> link joinmatrix.org for "find an existing server"

content/blog/2023/08/2023-08-04-twim.md
@thibaultamartin told me that Matrix live is still pending. Therefor it is commented for now. :)
=> Publish TWIM 20230804

content/blog/2023/08/2023-08-04-twim.md
Conduit accidentally was moved into the wrong section :)
=> Move conduit into the correct section

content/ecosystem/clients/nheko.md
ref. https://github.com/Nheko-Reborn/nheko/issues/489
=> nheko doesn't support multi-account

content/docs/legacy/matrix-bot-sdk-intro.md, content/docs/legacy/matrix-bot-sdk-room-admin-features.md, content/docs/legacy/moderation/index.md, content/docs/legacy/python-nio.md, sass/_legacy-docs.scss, templates/docs/legacy.html
=> Tone down legacy warning

content/docs/older/e2ee-cross-signing.md, content/docs/older/free-small-matrix-server.md, content/docs/older/map-tile-server.md, content/docs/older/stateres-v2.md, sass/_docs.scss, static/js/docs.js, templates/docs/legacy.html, templates/docs/with_menu.html
=> Fix the left menu scrolling with page content

sass/_base.scss, static/js/docs.js
=> Save scroll position before hiding and restoring content

content/ecosystem/bridges/groupme/bridges.toml
=> Fix groupme bridge data

content/ecosystem/clients/element-x.md, content/ecosystem/clients/element-x.svg
=> Add Element X

content/ecosystem/sdks/index.md
"If you are a developer and are not sure what the difference between clients and appservices, please head to the developers documentation."
#2079 issue, (BUG)... i have tried to solve that
=> Update Matrix.org-SDKs Documentation

templates/macros/atom.html
This should fix #2082 
Doing this right before changing trains so I didnt test it yet :D
=> Fix feed authors

content/ecosystem/integrations/integrations.toml
This adds draupnir to the list :)
=> Add Draupnir to the integrations list

content/ecosystem/bridges/zulip/_index.md, content/ecosystem/bridges/zulip/bridges.toml, content/ecosystem/bridges/zulip/logo.svg
=> Zulip bridge

content/ecosystem/clients/fractal.md
And update the date of the latest release at the same time.
=> Update link to Fractal repo

templates/shortcodes/howitworks.html
=> fix unhidden text on animation #2134

templates/skel.html
Reasoning behind the deployment of the analytics: https://ergaster.org/posts/2024/01/24-tracking-what-works/
=> Deploy privacy preserving web analytics on matrix.org

templates/index.html
Drop the supporters section entirely from the index since it's a Platinum member perk and we don't have any as of now
=> Drop supporters section from the index

content/ecosystem/sdks/sdks.toml
This PR adds LibMatrix to the list of SDKs.
=> Add SDK: LibMatrix CSharp

sass/_try-matrix.scss, templates/try-matrix.html
=> Improve the Try Matrix page

content/ecosystem/bridges/slack/bridges.toml
=> Fix typo in bridges.toml

content/ecosystem/hosting/index.md
probably? ref https://github.com/matrix-org/matrix-spec-proposals/pull/2997#issuecomment-774747896
maybe as native english speaker @joshsimmons should review.
=> Fix wording on ecosystem/hosting/index.md

content/ecosystem/bridges/signal/bridges.toml
The bridge has been rewritten in Go. Link to the docs has been fixed.
=> Update bridges.toml for Mautrix-Signal

content/ecosystem/clients/kazv.md, content/ecosystem/sdks/sdks.toml
Putting it all here, we finally got a release.
=> Update information about kazv and libkazv

sass/_support.scss
=> Fix supporters flexbox width

content/about/staff.toml
See https://github.com/matrix-org/matrix.org/pull/2244
=> Add socials for TravisR

static/assets/spec-logo.svg
=> Fix white spec-logo on off-white background

content/ecosystem/clients/iamb.md, content/ecosystem/clients/iamb.svg
This updates the information for iamb for its v0.0.9 release, and adds an icon to show for it.
=> Update iamb information for v0.0.9 release

navigation.toml, static/assets/rss.svg
Added RSS feed button to footer.
- Closes #2107
=> Add RSS feed button to footer

content/blog/2024/03/2024-03-08-twim.md
To respect this name change, I'd like to update the mention in my past announcement
=> Contributor name change

content/docs/chat_basics/private-group-chat/_index.md, content/docs/chat_basics/public-rooms/_index.md, content/docs/communities/moderation/_index.md, content/docs/matrix-concepts/end-to-end-encryption/_index.md, content/docs/matrix-concepts/rooms_and_events/_index.md
Minor fixes for mostly typos while reading the docs
=> Minor wording and typo fixes on docs

content/blog/2024/02/2024-02-20-website-office-hours.md
This makes sure we actually have the correct timeslot despite the summer/winter time changes in Europe.
=> Clarify the Timeslot with the summertime changes

content/governing-board/elections/2024/index.md, content/governing-board/elections/2024/nominees.toml, sass/_blog.scss, sass/_elections.scss, sass/_fonts.scss, sass/style.scss, templates/governing-board/elections.html, templates/index.html, templates/macros/nominee.html
=> Add a page dedicated to Elections information

content/blog/2024/04/2024-04-12-election-announcement.md, content/governing-board/elections/2024/index.md
correcting some language that suggested voting begins on the 17th. thanks for spotting that, @HarHarLinks!
=> clarify deadline is when voter rolls are made

content/governing-board/elections/2024/index.md, content/governing-board/elections/2024/nominees.toml, templates/governing-board/elections.html, templates/macros/nominee.html
=> introducing 2024 nominees (and bug fixes)

content/blog/2024/05/2024-05-10-twim.md
Just a quick fix to a couple of typos and one sentence in the widget section of this week's TWIM.
=> Adjust a couple of typos on the TWIM widget section

content/blog/2024/05/2024-05-17-voting-begins.md, content/governing-board/elections/2024/index.md
for publication after voting starts and before TWIM. I think I covered all the necessary details, feedback welcome!
=> election updates, voting has started

content/twim-guide.md
This adds a twim guide over at /twim-guide.
Its intentional to not be linked as it is going to be linked as part of twim posts.
cc @HarHarLinks if you have time to also review this :)
=> Add a guide for TWIM

content/twim-guide.md
=> Fix a typo

static/assets/frontpage/federation-visual.svg
=> Remove stray line from network visualization

content/blog/2024/05/2024-05-24-twim.md
what have i done, dear editor, to deserve having you remove all my links? 🙈
=> Fix events in 2024-05-24-twim.md

sass/_projects.scss
|Before|After|
|---|---|
|![image](https://github.com/matrix-org/matrix.org/assets/6900601/c01bbbc5-cec3-4913-849e-3e820aed16dd)|![image](https://github.com/matrix-org/matrix.org/assets/6900601/eddaaa17-4c0d-4b8c-b238-aa3c4c86f374)|
=> Centre client project names that span 2 lines

content/ecosystem/sdks/sdks.toml
@MTRNord 
These were causing build failures.
See <https://github.com/matrix-org/matrix.org/pull/2271>.
=> Fix: (sdks.toml) Unclosed quotations

.github/workflows/zola.yml, templates/ecosystem/clients.html
=> Fix ement.el breaking due to invalid html (a inside of a)

content/blog/2024/07/2024-07-17-twim.md
Clearly last friday was a bit too long for me...
=> Fix TWIM path

sass/_header.scss
=> Add a missing display flex to ensure the submenu hover works on 1x 1440p

content/ecosystem/integrations/integrations.toml
I am taking on day to day maintenance of this repo
=> update url and maintainer tag for matrix-rss-bridge

content/blog/2024/08/2024-08-09-twim.md
Some fixes @HarHarLinks asked me to do :)
=> Small adjustments

content/twim-guide.md
Signed-off-by: Gnuxie <Gnuxie@protonmail.com>
=> Be more specific about what correct linking is in the TWIM guide.

content/blog/2024/08/2024-08-15-heart-of-matrix.md
Signed-off-by: Andy Balaam <andy.balaam@matrix.org>
=> Fix typo: at->and

content/docs/older/matrix-bot-sdk-intro.md
Signed-off-by: Nikhil Nawgiri <the@realest.ninja>
=> Update matrix-bot-sdk-intro.md: Fix typo

content/ecosystem/servers/servers.toml, sass/_projects.scss, templates/ecosystem/clients.html, templates/macros/sdks.html, templates/section.html, templates/shortcodes/all_servers.html
=> Misc fixes

templates/blog.html, templates/post.html
=> Show all categories on blog.html

content/blog/2024/08/2024-08-15-heart-of-matrix.md
I had trouble understanding this sentence and found it easier when I made it "even if" to emphasise that the Foundation already does support these projects, and will continue if a competing fork emerges.
Signed-off-by: Andy Balaam <andy.balaam@matrix.org>
=> Attempt to clarify wording of what the Foundation will do.

content/blog/2024/10/2024-10-07-matrix-v1.12-release.md
https://github.com/matrix-org/matrix-spec/issues/1958
=> Matrix 1.12

content/blog/2024/10/2024-10-18-twim.md
see also https://github.com/matrix-org/twim-config/pull/24
=> Continue reading.... and fix up 2024-10-18-twim.md

content/ecosystem/integrations/integrations.toml
using etke.cc's fork: https://github.com/etkecc/synapse-admin/
=> Add Synapse Admin to integrations

content/blog/2024/11/2024-11-14-sunsetting-sliding-sync-proxy.md
=> It is November!

content/ecosystem/clients/schildichat-next.md, content/ecosystem/clients/schildichat-next.svg
Element X is currently listed as a separate client to Element, so I guess it makes sense to also have a dedicated entry for SchildiChat Next.
=> Add SchildiChat Next

content/blog/2024/10/2024-10-18-twim.md
=> Linkify in Update 2024-10-18-twim.md

content/blog/2024/10/2024-10-29-matrix-2.0-is-here.md
=> Continue reading... 2024-10-29-matrix-2.0-is-here.md

content/blog/2024/11/2024-11-04-fosdem-cfp.md
=> Add FOSDEM categories to 2024-11-04-fosdem-cfp.md

content/blog/2024/12/2024-12-03-unrelated-cybercriminal-network-taken-down.md
Add a link to the official Dutch comms confirming that there is no relation.
=> link to official statement disambiguating

content/ecosystem/sdks/sdks.toml
=> Add POSIX Shell Matrix SDK

content/security-hall-of-fame/findings.toml
- Remove trailing slashes from Github profile links
- Add missing spaces
- Uniformise CVE links to cve.org
=> Tidy up minor HoF inconsistencies

content/docs/matrix-concepts/rooms_and_events/_index.md
This seems unintentional?
Signed-off-by: Rasmus Praestholm <cervator@gmail.com>
=> Fix double negative

content/blog/2024/12/2024-12-19-matrix-v1.13-release.md
=> Continue reading... 2024-12-19-matrix-v1.13-release.md

content/blog/2024/12/2024-12-20-twim.md
=> Linkify 2024-12-20-twim.md

content/blog/2025/01/2025-01-06-authentication-changes.md
=> Read more... 2025-01-06-authentication-changes.md

content/security-hall-of-fame/findings.toml
Adds an older entry after getting an OK from the reporter.
=> Add older hall of fame entry

content/blog/2024/11/2024-11-19-matrix-fosdem-full-force.md
=> Fix health policy on 2024-11-19-matrix-fosdem-full-force.md

content/blog/2025/03/2025-03-07-twim.md
=> Fix up 2025-03-07-twim.md

content/blog/2025/02/2025-02-21-twim.md
=> Continue reading... 2025-02-21-twim.md

content/blog/2025/03/2025-03-27-matrix-v1.14-release.md
=> Continue reading... 2025-03-27-matrix-v1.14-release.md

static/funding.json
=> fix funding.json morg-spec repositoryUrl.wellKnown location

static/funding.json
=> Fix typos in funding.json

content/blog/2025/04/2025-04-02-matrix-auth-service.md
=> Fix category of 2025-04-02-matrix-auth-service.md

content/foundation/governing-board/index.md, content/foundation/working-groups/working_groups.toml
=> Update the GB and WG page

content/blog/2025/04/2025-04-17-introducing-policy-servers.md
Signed-off-by: Jim Mackenzie <jimm@element.io>
=> Introducing policy servers

CONTRIBUTING.md, content/foundation/working-groups/working_groups.toml
=> Name the Website and Content WG as repo maintainers instead of individuals

navigation.toml
As decided by the Working Group on 2025-04-24
https://matrix.discourse.group/t/website-wg-meeting-minutes/131/9
=> Rename Donate to Support us in navbar

content/blog/2025/04/2025-04-28-election-announcement.md
=> fix a missing space

templates/index.html
=> remove leftover variable

content/blog/2025/05/2025-05-16-twim.md
=> fix link to mc25 cfp

content/support/supporters.toml
=> drop Futurewei, re-alphabetize Silver Members

content/blog/2025/05/2025-05-23-twim.md, content/blog/2025/05/2025-05-25-governing-board-report-may-25.md
=> Blog fixes

static/_headers
- set content type JSON as is REQUIRED by spec ([client](https://spec.matrix.org/v1.14/client-server-api/#web-browser-clients), [server](https://spec.matrix.org/v1.14/server-server-api/#api-standards))
- set CORS headers as recommended by https://spec.matrix.org/v1.14/client-server-api/#web-browser-clients
=> Update .well-known headers

content/ecosystem/servers/servers.toml
Opening on behalf of the [continuwuity team](https://forgejo.ellis.link/org/continuwuation/members).
=> Add continuwuity to servers.toml

config.toml
cfp is over, now awaiting schedule
=> update matrix conf phase

CONTENT.md
=> Document continue reading marker in CONTENT.md

content/blog/2025/07/2025-07-11-twim.md
As Sky points out, dept of ping was missing from TWIM.
=> amend dept of ping to TWIM 20250711

content/homeserver/about.md
Fixes some links, thanks @tulir for reporting.
Could've continued with relative links `../official` etc, maybe that woulda worked, but I feel like at least when checking manually we are more likely to find wrong absolute (still internal) links.
=> Fix relative links in homeserver/about.md

content/blog/2025/07/2025-07-18-twim.md
adding TWIM, today with correct headings and ping stats
=> add TWIM 2025-07-18

content/support/polycule.svg, content/support/supporters.toml
feat: adds < polycule > as ecosystem member
=> feat: adds < polycule > as ecosystem member

content/blog/2025/07/2025-07-25-twim.md
Adding the report of the week, with pings even!
=> Add TWIM 2025-07-25

content/homeserver/pricing.md, sass/_base.scss
Signed-off-by: Hugh Nimmo-Smith <hughns@element.io>
=> Document the per day/per month data limit for matrix.org homeserver

content/homeserver/pricing.md
Signed-off-by: Hugh Nimmo-Smith <hughns@element.io>
=> Maximum file size limit of Free usage plan is increased to 10MB

content/foundation/working-groups/working_groups.toml
Memberlist for the room dir working group is not complete yet, since not all members have signed off on being publicly listed yet. Room directory policy also needs to be added in a follow up.
=> Add Room Dir and T&S R&D working groups

content/homeserver/pricing.md
Three changes:
- attempts to clarify that usage limits will be different for Free and Premium usage plans when they are introduced
- be consistent with the time periods associated with the limits (day = 24 hours, month = 28 days)
- add a link to the newly available usage limits view
Signed-off-by: Hugh Nimmo-Smith <hughns@element.io>
=> Clarification around how the fair usage limits apply

content/ecosystem/_index.md, templates/ecosystem.html
Autogenerates the /ecosystem page from the existing data annotations instead of hardcoding a redundant text.
Resolves #2197
Supersedes #2466
=> autogenerate the /ecosystem index page

content/foundation/governing-board/bylaws/02-bylaws.md, content/foundation/governing-board/index.md
:tophat: Vice Chair of The Matrix.org Foundation Governing Board
Reference (non-public link): https://matrix.discourse.group/t/flesh-out-wg-chairs-expectations-in-the-bylaws/161/4
CC @GregSutcliffe
This updates the bylaws of the Governing Board as decided on 2025-07-27, effective immediately.
As a follow-up, we might want to announce this to the world via TWIM, as it is intended to make it more accessible to the wider public to understand better how our working groups work.
=> Flesh out WG chairs expectations in the bylaws

content/homeserver/official.md, content/twim-guide.md, sass/_base.scss, sass/_index.scss, templates/shortcodes/notice_box.md
Resolves #2764 and also improves the guide a bit here and there.
=> Document the TWIM process

content/foundation/working-groups/index.md, content/foundation/working-groups/working_groups.toml
:tophat: Contributing as Vice Chair of the Governing Board
=> Add more info on WGs

content/blog/2025/08/2025-08-08-twim.md
=> Publish TWIM

content/docs/communities/administration/_index.md
I'm employee of Nordeck, member of the Events Working Group, Individual Foundation Member and Ecosystem Member for < polycule >. This PR is made in the name of < polycule > as an Ecosystem Member.
=> feat: add < polycule > to the room upgrade guide

content/foundation/governing-board/index.md, content/foundation/working-groups/working_groups.toml
(My as in responsible for, but subject length...)
=> Update chairs and members of my committees and WGs

content/docs/communities/administration/_index.md
:tophat: Website & Content WG (and [tune your chat](https://github.com/harharLinks/tune-your-chat) nerd)
This PR adds two tools that allow one to determine the support for room versions among the servers participating in a given room.
=> add room version checkers to upgrade guide

content/docs/communities/administration/_index.md
=> add Matrix Live with guidance about room version 12

content/foundation/working-groups/working_groups.toml
I (@sky:codestorm.net) am the chair of this WG and would like to update the list of our current members
=> Update member list of room directory working group

content/ecosystem/servers/servers.toml
Adding in Synapse Pro since it is at this point distinct to Synapse and important to the eco-system since it backs the matrix.org homeserver as well as multiple large scale and high profile government installations. 
Separately, I think we need a deterministic ordering for projects for all eco-system pages and I would support the approach Thib outlines [here](https://github.com/matrix-org/matrix.org/issues/1584), but for now, adding as is. 
Signed-off-by: Neil Johnson [neil@element.io](mailto:neilj@element.io)
=> Add in details of the Synapse Pro homeserver

CONTRIBUTING.md
This adds the Website Review & Publishing Policy
=> Add the Website Review & Publishing Policy

CONTENT.md, content/ecosystem/servers/servers.toml, templates/shortcodes/all_servers.html
Adds a button to website to the ecosystem/servers list to link to a homepage.
Counter-proposal to #2923, see https://github.com/matrix-org/matrix.org/pull/2923#issuecomment-3322648286
=> Add homepage button to ecosystem/servers

content/blog/2025/09/2025-09-26-twim.md
=> fixup twim

content/twim-guide.md
=> Improve TWIM guide changelog wording
